quantumlib/Qualtran

dev_tools/autogenerate-bloqs-notebooks.py, qualtran/bloqs/basic_gates.ipynb, qualtran/bloqs/basic_gates/__init__.py, qualtran/bloqs/basic_gates/toffoli.py, qualtran/bloqs/basic_gates/toffoli_test.py
Adds `Toffoli` to `bloqs.basic_gates`.
=> Add Toffoli

MANIFEST.in, qualtran/_version.py
- Set the version to a released version. I'll tag this commit when merged to `main`. 
- Need a manifest file for the sdist to work, so that's also included
- Then I'll open a PR to bump the version spec to `"0.2.0.dev0"`
=> Release v0.1

qualtran/_version.py
Following #331 and https://github.com/quantumlib/Qualtran/releases/tag/v0.1.0
=> Bump version to 0.2.0.dev0

dev_tools/autogenerate-bloqs-notebooks.py, qualtran/bloqs/basic_gates.ipynb, qualtran/bloqs/basic_gates/__init__.py, qualtran/bloqs/basic_gates/hadamard.py, qualtran/bloqs/basic_gates/hadamard_test.py, qualtran/bloqs/basic_gates/x_basis.py, qualtran/bloqs/basic_gates/x_basis_test.py, qualtran/bloqs/basic_gates/z_basis.py, qualtran/bloqs/basic_gates/z_basis_test.py
=> Add Hadamard Bloq

qualtran/bloqs/basic_gates/__init__.py, qualtran/bloqs/basic_gates/y_gate.py, qualtran/bloqs/basic_gates/y_gate_test.py
=> Add pauli Y.

qualtran/bloqs/arithmetic.py, qualtran/bloqs/arithmetic_test.py
Wrap some of cirqs comparators.
=> Less than equal bloqs.

qualtran/cirq_interop/_cirq_to_bloq.py, qualtran/cirq_interop/_cirq_to_bloq_test.py, qualtran/cirq_interop/_interop_qubit_manager.py, qualtran/cirq_interop/_interop_qubit_manager_test.py
Fixes https://github.com/quantumlib/Qualtran/issues/384
=> Add `InteropQubitManager` to use in Cirq/Bloqs interop code.

dev_tools/requirements/envs/dev.env.txt, dev_tools/requirements/envs/docs.env.txt, dev_tools/requirements/envs/format.env.txt, dev_tools/requirements/envs/pip-tools.env.txt, dev_tools/requirements/envs/pylint.env.txt, dev_tools/requirements/envs/pytest.env.txt, dev_tools/requirements/envs/runtime.env.txt
=> Bump dependencies in *.env.txt

qualtran/bloqs/unary_iteration.ipynb
Left over from https://github.com/quantumlib/Qualtran/pull/399
=> Use qualtran instead of cirq_ft in `unary_iteration.ipynb` notebook

qualtran/bloqs/selected_majorana_fermion.py, qualtran/bloqs/selected_majorana_fermion_test.py
=> Add `SelectedMajoranaFermion` Bloq from Cirq-FT

qualtran/bloqs/qrom.ipynb, qualtran/bloqs/qrom.py, qualtran/bloqs/qrom_test.py
=> Add `QROM` Bloq from Cirq-FT

qualtran/bloqs/programmable_rotation_gate_array.py, qualtran/bloqs/programmable_rotation_gate_array_test.py
=> Add `ProgrammableRotationGateArray` Bloq from Cirq-FT

dev_tools/autogenerate-bloqs-notebooks.py, qualtran/bloqs/arithmetic.ipynb, qualtran/bloqs/arithmetic.py, qualtran/bloqs/arithmetic_test.py
This is pulled out from the first quantization bloqs, implementation would be a good target for the community.
=> Signed to twos

dev_tools/requirements/deps/pytest.txt, dev_tools/requirements/envs/dev.env.txt, dev_tools/requirements/envs/docs.env.txt, dev_tools/requirements/envs/format.env.txt, dev_tools/requirements/envs/pylint.env.txt, dev_tools/requirements/envs/pytest.env.txt, dev_tools/requirements/envs/runtime.env.txt
Add openfermion to the pytest environment #395 and needed for #409
=> Add openfermion to pytest env.

qualtran/bloqs/arithmetic.py
Minor update, came up during my work on costing out QAOA.
=> Express cost of addition in terms of Toffoli's instead of T gates

dev_tools/autogenerate-bloqs-notebooks-v2.py, qualtran/bloqs/prepare_uniform_superposition.ipynb, qualtran/bloqs/prepare_uniform_superposition.py, qualtran/bloqs/prepare_uniform_superposition_test.py
Add `PrepareUniformSuperposition` examples
=> [autodoc/autotest] PrepareUniformSuperposition

dev_tools/bloq-report-card.ipynb, dev_tools/qualtran_dev_tools/bloq_finder.py, dev_tools/qualtran_dev_tools/bloq_report_card.py, dev_tools/qualtran_dev_tools/git_tools.py
Some dev-tools scripts for 
- running the `qualtran.testing.check_xxx` checks against all `BloqExample`s
- showing the results in a "report card"
=> Bloq report card

qualtran/bloqs/arithmetic.py, qualtran/bloqs/arithmetic_test.py
Similar to #468 , use the more natural cost.
=> TGate -> Toffoli for signed to twos.

qualtran/bloqs/unary_iteration_bloq.py, qualtran/bloqs/unary_iteration_bloq_test.py
Fixes https://github.com/quantumlib/Qualtran/issues/476
=> Fix T-complexity for UnaryIteration with 0 controls and larger selection bitsize

qualtran/_infra/registers.py, qualtran/bloqs/util_bloqs_test.py
Remove deprecation warnings about np.product (use np.prod)
=> Use np.prod not np.product.

qualtran/bloqs/arithmetic.py, qualtran/bloqs/arithmetic_test.py
Follows construction described on Page-4 of https://arxiv.org/abs/1709.06648
cc @ncrubin
=> Add `HammingWeightCompute` gate using 3-to-2 Gidney adders

dev_tools/bloq-report-card.ipynb, dev_tools/qualtran_dev_tools/bloq_report_card.py, qualtran/bloqs/basic_gates/cnot.py, qualtran/bloqs/basic_gates/cnot_test.py, qualtran/bloqs/basic_gates/hadamard.py, qualtran/bloqs/basic_gates/hadamard_test.py, qualtran/bloqs/basic_gates/rotation.py, qualtran/bloqs/basic_gates/rotation_test.py, qualtran/bloqs/basic_gates/z_basis.py, qualtran/bloqs/basic_gates/z_basis_test.py, qualtran/resource_counting/bloq_counts.py
Add `BloqExample`s for `qualtran.bloqs.basic_gates`.
=> [autotest] basic_gates

dev_tools/clean-notebooks.py, dev_tools/qualtran_dev_tools/clean_notebooks.py
Example script that can strip notebook metadata and optionally be used as a CI check. I didn't actually commit the results in this PR
=> Clean notebooks

qualtran/bloqs/mean_estimation/mean_estimation_operator.py, qualtran/bloqs/reflection_using_prepare.py
The $P$ and $P^{\dagger}$ should be reverse as pointed out by Aly.
=> Fix docstring for Reflection operator

qualtran/bloqs/util_bloqs.ipynb, qualtran/bloqs/util_bloqs.py, qualtran/bloqs/util_bloqs_test.py
Stripping out from #300 as a useful utility bloq for a follow up of #392. Writte by @mpharrigan I just added a test and an example to the notebook.
=> Add partition bloq

dev_tools/autogenerate-bloqs-notebooks-v2.py, dev_tools/autogenerate-bloqs-notebooks.py, dev_tools/qualtran_dev_tools/jupyter_autogen.py, qualtran/bloqs/and_bloq.ipynb, qualtran/bloqs/and_bloq.py, qualtran/bloqs/and_bloq_test.py
add bloq examples, bloq autotester, and notebooks v2 for the `and_bloq` module
=> [autodoc] And and MultiAnd

dev_tools/qualtran_dev_tools/reference_docs.py, qualtran/bloqs/arithmetic/comparison.py, qualtran/bloqs/arithmetic/multiplication.py, qualtran/bloqs/basic_gates/rotation.py, qualtran/bloqs/controlled_bloq.py, qualtran/bloqs/controlled_bloq_test.py, qualtran/bloqs/sorting.py
Name replacement for some issues and links.
=> cirq-qubitization -> Qualtran.

qualtran/bloqs/generalized_qsp.ipynb, qualtran/bloqs/generalized_qsp.py, qualtran/bloqs/generalized_qsp_test.py
theorem 4 of https://arxiv.org/abs/2308.01501
Still some debugging left to do:
=> GQSP: Implement complementary polynomial computation

qualtran/bloqs/qrom.py, qualtran/bloqs/qrom_test.py, qualtran/bloqs/unary_iteration_bloq.py, qualtran/bloqs/unary_iteration_bloq_test.py
Fixes https://github.com/quantumlib/Qualtran/issues/559
Inspired from https://github.com/quantumlib/Qualtran/pull/609
=> Add `build_callgraph` to `UnaryIterationGate`

qualtran/bloqs/and_bloq.py, qualtran/bloqs/and_bloq_test.py
=> Classical support for And().adjoint()

qualtran/bloqs/and_bloq.py, qualtran/bloqs/basic_gates/toffoli.py, qualtran/bloqs/basic_gates/x_basis.py, qualtran/bloqs/basic_gates/z_basis.py, qualtran/bloqs/on_each.py
Working on #446 and following on from adding the types in #624 I'll start incrementally replacing registers bitsizes with dtypes. Here I just take care of basic_gates, and and on_each
=> [data types] Simple data types

qualtran/__init__.py, qualtran/_infra/data_types.py, qualtran/_infra/data_types_test.py, qualtran/bloqs/factoring/mod_add.py, qualtran/bloqs/factoring/mod_exp.py
=> [data types] Add dtypes to factoring bloqs.

qualtran/bloqs/arithmetic/addition.py
=> [data types] Addition bloqs

qualtran/bloqs/arithmetic/comparison.py
Depends on #638.
@NoureldinYosri I wasn't sure what the data types of the registers should be for the comparators (or maybe they work for all integer types, ones / twos complement, ...). For the moment the types don't enforce anything but would be good to track in #637
=> [data types] Migrate comparison gates

dev_tools/autogenerate-bloqs-notebooks-v2.py, qualtran/bloqs/arithmetic/conversions.ipynb, qualtran/bloqs/arithmetic/conversions.py, qualtran/bloqs/arithmetic/conversions_test.py
Also update tests to use new autotesting + add notebook. Depends on #639
=> [data types] Migrate conversions bloqs

qualtran/bloqs/arithmetic/hamming_weight.py, qualtran/bloqs/qft/qft_phase_gradient.py, qualtran/bloqs/qft/qft_text_book.py, qualtran/bloqs/rotations/hamming_weight_phasing.py, qualtran/bloqs/rotations/phase_gradient.py
* Sneak in: Shorten QFixedPoint -> QFxP, add QUFxP (#632)
* Updated registers for HammingWeightCompute.
=> [data types] Add data types for rotation and QFT bloqs

dev_tools/autogenerate-bloqs-notebooks-v2.py, qualtran/bloqs/arithmetic/multiplication.ipynb, qualtran/bloqs/arithmetic/multiplication.py, qualtran/bloqs/arithmetic/multiplication_test.py
I noticed during #642 that there were some errors in the docs. Also add autotesting for each.
=> Update multiplication docs.

qualtran/bloqs/select_pauli_lcu_test.py, qualtran/bloqs/state_preparation/state_preparation_alias_sampling.py, qualtran/bloqs/state_preparation/state_preparation_alias_sampling_test.py
Fixes https://github.com/quantumlib/Qualtran/issues/682
=> Bufix in decomposition of `StatePreparationAliasSampling` when `self.mu == 0`

qualtran/serialization/data_types.py
Addresses follow up comment in #671.
=> Remove unecessary function.

qualtran/surface_code/ui.py
Updated the title from "Interactive Quantum Resource Estimation" to "Interactive QEC overhead estimation", which more accurately reflects the scope of the UI right now
=> Update title of QEC overhead estimation UI

dev_tools/qualtran_dev_tools/jupyter_autogen_v2.py, qualtran/_infra/bloq_example.py, qualtran/bloqs/chemistry/df/double_factorization.ipynb, qualtran/bloqs/data_loading/qrom.ipynb
=> Fix jupyter autogen source parsing

qualtran/bloqs/data_loading/__init__.py
I forgot to `git add` it as part of my previous PR to organize QROMs https://github.com/quantumlib/Qualtran/pull/752
=> Add init.py to data loading module

dev_tools/requirements/envs/dev.env.txt, dev_tools/requirements/envs/docs.env.txt, dev_tools/requirements/envs/format.env.txt, dev_tools/requirements/envs/pip-tools.env.txt, dev_tools/requirements/envs/pylint.env.txt, dev_tools/requirements/envs/pytest.env.txt, dev_tools/requirements/envs/runtime.env.txt, qualtran/bloqs/chemistry/trotter/hubbard/hubbard.ipynb, qualtran/bloqs/qubitization_walk_operator.ipynb, qualtran/bloqs/state_preparation/state_preparation_alias_sampling.ipynb
in particular, the `qsharp` dependency didn't actually get fully picked up when that was committed.
=> 2024-03 Housekeeping

qualtran/conftest.py, qualtran/protos/args.proto, qualtran/protos/args_pb2.py, qualtran/protos/args_pb2.pyi, qualtran/protos/bloq.proto, qualtran/protos/bloq_pb2.py, qualtran/protos/bloq_pb2.pyi, qualtran/serialization/args.py, qualtran/serialization/args_test.py, qualtran/serialization/bloq.py
fixes https://github.com/quantumlib/Qualtran/issues/829
=> serialize `complex` bloq arguments

qualtran/bloqs/generalized_qsp.ipynb, qualtran/bloqs/generalized_qsp.py, qualtran/bloqs/generalized_qsp_test.py
https://github.com/quantumlib/Qualtran/pull/669#discussion_r1529232191
=> [GQSP] support negative powers

dev_tools/requirements/deps/runtime.txt, dev_tools/requirements/envs/dev.env.txt, dev_tools/requirements/envs/docs.env.txt, dev_tools/requirements/envs/format.env.txt, dev_tools/requirements/envs/pip-tools.env.txt, dev_tools/requirements/envs/pylint.env.txt, dev_tools/requirements/envs/pytest.env.txt, dev_tools/requirements/envs/runtime.env.txt
Update cirq version to incorporate bugfix in clean ancilla allocations from https://github.com/quantumlib/Cirq/pull/6554
=> Update cirq version and recompile dependencies

qualtran/surface_code/ui_test.py
follow-up to https://github.com/quantumlib/Qualtran/pull/871
=> Add unit tests for ui.format_duration

qualtran/bloqs/basic_gates/global_phase.py, qualtran/bloqs/basic_gates/su2_rotation.py, qualtran/bloqs/basic_gates/swap.py, qualtran/bloqs/basic_gates/y_gate.py
=> add missing adjoints for basic gates

dev_tools/requirements/envs/dev.env.txt, dev_tools/requirements/envs/docs.env.txt, dev_tools/requirements/envs/format.env.txt, dev_tools/requirements/envs/pylint.env.txt, dev_tools/requirements/envs/pytest.env.txt, dev_tools/requirements/envs/runtime.env.txt
Just regularly scheduled maintenance in the pinned dependencies (used for the CI)
=> 2024-05 Bump Dependencies

qualtran/bloqs/chemistry/black_boxes.py, qualtran/bloqs/chemistry/black_boxes_test.py, qualtran/bloqs/chemistry/chem_tutorials.py
This is a refactoring to better understand and express the cost of QROAM blackbox. I used these changes to figure out the discrepency between SelectSwapQROM cost and QROAM costs and I think it's worth committing these changes so they don't get lost in my git stash. 
Eventually, we'll get rid of `QROAM` so this would be moot.
=> Refactor formula for getting costs of QROAM

qualtran/bloqs/arithmetic/__init__.py, qualtran/bloqs/arithmetic/_shims.py, qualtran/bloqs/arithmetic/addition.py, qualtran/bloqs/arithmetic/addition_test.py, qualtran/bloqs/arithmetic/subtraction.py, qualtran/bloqs/arithmetic/subtraction_test.py, qualtran/bloqs/mod_arithmetic/_shims.py
- put in its own module
- remove the reference since the construction isn't based off of it
- un-mark the test as slow since it was pretty quick on my machine
- remove the `Sub` shim
=> [arithmetic] Organize `Subtract`

dev_tools/autogenerate-bloqs-notebooks-v2.py, docs/bloqs/index.rst, qualtran/bloqs/arithmetic/subtraction.ipynb, qualtran/bloqs/chemistry/trotter/hubbard/hubbard.ipynb, qualtran/bloqs/chemistry/trotter/hubbard/interaction.py, qualtran/bloqs/hamiltonian_simulation/hamiltonian_simulation_by_gqsp.ipynb
Some stale notebooks + missing subtraction.ipynb and some missing docs from the new bloqs in #946.
=> Notebook updates

qualtran/bloqs/chemistry/thc/thc.ipynb, qualtran/bloqs/data_loading/select_swap_qrom_test.py, qualtran/resource_counting/t_counts_from_sigma.py
Fixes https://github.com/quantumlib/Qualtran/issues/779
=> Bugfix in `t_counts_from_sigma` to also count up `T.adjoint()` bloqs

qualtran/_infra/registers.py
=> Update docs for `Register`

qualtran/bloqs/arithmetic/conversions.py, qualtran/bloqs/chemistry/df/double_factorization.py, qualtran/bloqs/chemistry/pbc/first_quantization/prepare_nu.py, qualtran/bloqs/chemistry/pbc/first_quantization/prepare_t.py, qualtran/bloqs/chemistry/pbc/first_quantization/prepare_uv.py, qualtran/bloqs/chemistry/pbc/first_quantization/projectile/prepare_uv.py, qualtran/bloqs/chemistry/pbc/first_quantization/projectile/select_t.py, qualtran/bloqs/chemistry/pbc/first_quantization/select_t.py, qualtran/bloqs/chemistry/pbc/first_quantization/select_uv.py
=> Change diagrams to use ascii math

qualtran/bloqs/hubbard_model_test.py, qualtran/bloqs/phase_estimation/qubitization_qpe_test.py
This got left out from https://github.com/quantumlib/Qualtran/pull/1003, not sure how the CI didn't complain.
=> Move `test_phase_estimation_of_qubitized_hubbard_model` to `phase_estimation/`

qualtran/bloqs/mcmt/and_bloq.ipynb, qualtran/bloqs/reflections/reflections.ipynb
Simply ran `python dev_tools/autogenerate-bloqs-notebooks-v2.py` to update some of the stale notebooks.
=> Regenerate notebooks using autogenerate script

qualtran/bloqs/arithmetic/comparison.py, qualtran/bloqs/arithmetic/comparison_test.py
pulled out from https://github.com/quantumlib/Qualtran/pull/1017
Fixes issue raised in https://github.com/quantumlib/Qualtran/pull/1018
=> Fix symbolic resource estimation for comparison gates

qualtran/bloqs/mcmt/multi_control_multi_target_pauli.py, qualtran/bloqs/mcmt/multi_control_multi_target_pauli_test.py
Pulled out from https://github.com/quantumlib/Qualtran/pull/1017
=> Add build_call_graph and symbolic resource estimation to MultiControlPauli

qualtran/bloqs/hamiltonian_simulation/hamiltonian_simulation_by_gqsp_test.py, qualtran/bloqs/qsp/fast_qsp_test.py, qualtran/bloqs/qsp/generalized_qsp_test.py
=> [GQSP] unmark not so slow "slow" tests

qualtran/bloqs/arithmetic/hamming_weight_test.py, qualtran/bloqs/chemistry/sparse/sparse_test.py, qualtran/bloqs/data_loading/select_swap_qrom_test.py, qualtran/bloqs/hamiltonian_simulation/hamiltonian_simulation_by_gqsp_test.py
=> Unmark some slow tests that aren't actually slow

dev_tools/requirements/envs/dev.env.txt, dev_tools/requirements/envs/docs.env.txt, dev_tools/requirements/envs/format.env.txt, dev_tools/requirements/envs/pip-tools.env.txt, dev_tools/requirements/envs/pylint.env.txt, dev_tools/requirements/envs/pytest.env.txt, dev_tools/requirements/envs/runtime.env.txt
Regularly scheduled maintenance
=> 2024-06 Bump Dependencies

qualtran/bloqs/basic_gates/z_basis.py, qualtran/bloqs/qsp/generalized_qsp.py, qualtran/conftest.py, qualtran/serialization/resolver_dict.py, qualtran/serialization/sympy.py
- Remove working tests from the skip list
- Fix `HamiltonianSimulationByGQSP` serialization (added to resolverdict)
=> Update skiplist for serialization examples

qualtran/bloqs/state_preparation/state_preparation_alias_sampling.py
From offline discussions @tanujkhattar @charlesyuan314 feel free to ignore
=> Add a note to StatePreparationAliasSampling

qualtran/bloqs/chemistry/trotter/hubbard/hopping.py, qualtran/bloqs/chemistry/trotter/hubbard/interaction.py, qualtran/bloqs/chemistry/trotter/trotterized_unitary.py, qualtran/bloqs/rotations/hamming_weight_phasing.py, qualtran/bloqs/rotations/quantum_variable_rotation.py
Replace some instances of `Union[T]` with just `T`.
=> Remove unnecessary `Union`

qualtran/serialization/resolver_dict.py
Add these imports for consistency with all other imported modules in this file and to dismiss IDE warnings.
=> Add imports in `resolver_dict`

qualtran/bloqs/data_loading/qrom_base.py, qualtran/bloqs/data_loading/qrom_test.py
This got missed from https://github.com/quantumlib/Qualtran/pull/1160
=> Fix classical simulation when selection bitsize is 0 for QROM

qualtran/bloqs/arithmetic/comparison.py, qualtran/drawing/qpic_diagram.py
Add otimes convert for OnEach and replaces ^ with unicode ^ for comparison gates, and use $\le$ $\ge$
=> Update QPIC \otimes and ^

qualtran/bloqs/qsp/generalized_qsp.py
This was done in https://github.com/quantumlib/Qualtran/pull/930
=> Remove GQSP todo

qualtran/bloqs/block_encoding/chebyshev_polynomial.py, qualtran/bloqs/block_encoding/chebyshev_polynomial_test.py, qualtran/bloqs/for_testing/matrix_gate.py, qualtran/linalg/matrix.py
- Switch from `GlobalPhase` back to `ReflectionUsingPrepare` for the correct reflection operator
- Add tests generated from random Hermitian matrices of norm <= 1.
=> Fix and add random tests for `ChebyshevPolynomial`

qualtran/resource_counting/_bloq_counts.py, qualtran/resource_counting/_bloq_counts_test.py
It's convenient to get these as a dictionary sometimes (without zeros so not just straight attrs.asdict)
=> Add asdict for GateCounts

dev_tools/autogenerate-bloqs-notebooks-v2.py, qualtran/bloqs/block_encoding/__init__.py, qualtran/bloqs/block_encoding/lcu_block_encoding.ipynb, qualtran/bloqs/block_encoding/lcu_block_encoding.py, qualtran/bloqs/block_encoding/lcu_block_encoding_test.py, qualtran/bloqs/block_encoding/linear_combination.py, qualtran/bloqs/chemistry/resource_estimation.ipynb, qualtran/bloqs/multiplexers/black_box_select.py, qualtran/bloqs/multiplexers/black_box_select_test.py, qualtran/bloqs/state_preparation/black_box_prepare.py, qualtran/bloqs/state_preparation/black_box_prepare_test.py, qualtran/serialization/resolver_dict.py
Move these two classes for consistency with the classes they typically co-occur with.
=> Move `BlackBox{Select,Prepare}` next to `{Select,Prepare}Oracle`

qualtran/bloqs/multiplexers/black_box_select.py, qualtran/bloqs/state_preparation/black_box_prepare.py, qualtran/conftest.py
Simplify `BlackBox{Select,Prepare}` decomposition using `AutoPartition`.
=> Use `AutoPartition` in `BlackBox`

qualtran/protos/data_types.proto, qualtran/protos/data_types_pb2.py, qualtran/protos/data_types_pb2.pyi, qualtran/serialization/data_types.py, qualtran/serialization/data_types_test.py
=> Serialize QMontgomeryUInt

qualtran/linalg/permutation_test.py
Adding tests to catch the (fixed) infinite loop bug: https://github.com/quantumlib/Qualtran/pull/1205/files#r1722422347
=> Add more permutation tests

qualtran/bloqs/basic_gates/su2_rotation.py, qualtran/bloqs/hamiltonian_simulation/hamiltonian_simulation_by_gqsp.py, qualtran/bloqs/hamiltonian_simulation/hamiltonian_simulation_by_gqsp_test.py, qualtran/bloqs/state_preparation/sparse_state_preparation_via_rotations.py, qualtran/bloqs/state_preparation/sparse_state_preparation_via_rotations_test.py, qualtran/linalg/polynomial/jacobi_anger_approximations.py, qualtran/linalg/polynomial/qsp_testing.py
There are a bunch of problems with our dependencies, but we'll at least need these changes to the qualtran code to support numpy 2
=> Numpy 2 anticipatory fixes

qualtran/_infra/controlled_test.py
Prompted by my own review of #1320! Use `ctrl_bloq` for controlled bloqs. Save `cbloq` to refer to a composite bloq.
=> [style] Only use "cbloq" for composite bloqs

qualtran/bloqs/arithmetic/controlled_addition.py, qualtran/bloqs/arithmetic/controlled_addition_test.py
context: https://github.com/quantumlib/Qualtran/issues/1309#issuecomment-2299843007
The old tcomplexity annotation represented the buggy original decomposition from https://github.com/quantumlib/Qualtran/pull/864
=> Fix  and improve CAdd tests

qualtran/bloqs/hamiltonian_simulation/hamiltonian_simulation_by_gqsp.ipynb, qualtran/bloqs/hamiltonian_simulation/hamiltonian_simulation_by_gqsp.py, qualtran/bloqs/hamiltonian_simulation/hamiltonian_simulation_by_gqsp_test.py, qualtran/bloqs/qsp/generalized_qsp.ipynb, qualtran/bloqs/qsp/generalized_qsp.py
Used to decide the precision of each single qubit rotation
=> Add precision parameter to GQSP

qualtran/bloqs/basic_gates/on_each.py
concludes work on https://github.com/quantumlib/Qualtran/issues/1230
=> document new OnEach argument

qualtran/bloqs/for_testing/qubitization_walk_test.py
Fix a typing problem that is causing the [nightly tests to fail](https://github.com/quantumlib/Qualtran/actions/runs/10576856467/job/29303562603).
=> Fix `selection_registers` in `qubitization_walk_test`

qualtran/bloqs/block_encoding/product.py, qualtran/bloqs/block_encoding/product_test.py
See https://github.com/quantumlib/Qualtran/issues/1309#issuecomment-2313695831.
=> Add symbolic call graph for `Product` block encoding

qualtran/bloqs/chemistry/trotter/grid_ham/trotter_costs.ipynb, qualtran/drawing/__init__.py, qualtran/drawing/_show_funcs.py, qualtran/drawing/bloq_counts_graph.py, qualtran/drawing/bloq_counts_graph_test.py, qualtran/drawing/drawing_call_graph.ipynb
- This has been replaced by GraphvizCallGraph.
Fixes: #791
=> Remove GraphvizCounts

dev_tools/autogenerate-bloqs-notebooks-v2.py, qualtran/bloqs/arithmetic/__init__.py, qualtran/bloqs/arithmetic/comparison.ipynb, qualtran/bloqs/arithmetic/comparison.py, qualtran/bloqs/arithmetic/comparison_test.py, qualtran/serialization/resolver_dict.py
Adds bloq to check if two quantum registers are equal.
=> Add Equals() bloq

qualtran/bloqs/mod_arithmetic/mod_addition_test.py
followup to https://github.com/quantumlib/Qualtran/pull/1424
=> Add classical action test for ModAdd

dev_tools/qualtran_dev_tools/notebook_specs.py, docs/bloqs/index.rst, qualtran/bloqs/rotations/__init__.py, qualtran/bloqs/rotations/rz_via_phase_gradient.ipynb, qualtran/bloqs/rotations/rz_via_phase_gradient.py, qualtran/bloqs/rotations/rz_via_phase_gradient_test.py, qualtran/bloqs/rotations/zpow_via_phase_gradient.ipynb, qualtran/bloqs/rotations/zpow_via_phase_gradient.py, qualtran/bloqs/rotations/zpow_via_phase_gradient_test.py, qualtran/serialization/resolver_dict.py
=> notebooks for `ZPowConstViaPhaseGradient` and `RzViaPhaseGradient`

dev_tools/requirements/envs/dev.env.txt, dev_tools/requirements/envs/docs.env.txt, dev_tools/requirements/envs/format.env.txt, dev_tools/requirements/envs/pip-tools.env.txt, dev_tools/requirements/envs/pylint.env.txt, dev_tools/requirements/envs/pytest.env.txt, dev_tools/requirements/envs/runtime.env.txt, qualtran/_infra/controlled.py, qualtran/bloqs/multiplexers/apply_lth_bloq.py, qualtran/bloqs/multiplexers/selected_majorana_fermion.py, qualtran/cirq_interop/_bloq_to_cirq.py, qualtran/cirq_interop/_cirq_to_bloq.py
Regularly scheduled maintenance
=> 2024-12 Bump Dependencies

dev_tools/requirements/deps/runtime.txt
=> Setting min version of attrs

qualtran/bloqs/block_encoding/sparse_matrix_test.py
Reduces the input size for `test_matrix_stress` so that the tensors can be computed.
For the old parameters, the nightly fails with a memory error:
```
FAILED qualtran/bloqs/block_encoding/sparse_matrix_test.py::test_matrix_stress - numpy.core._exceptions._ArrayMemoryError: Unable to allocate 64.0 GiB for an array with shape (16, 131072, 2048) and data type complex128
```
=> Fix memory overflow in sparse matrix stress test

qualtran/_infra/data_types.py, qualtran/_infra/data_types_test.py
fixes https://github.com/quantumlib/Qualtran/issues/1538
=> make QGF with irreducible_poly=None compatible with QGF with the correct poly

dev_tools/ui-export.ipynb, qualtran/_infra/bloq_example.py, qualtran/bloqs/cryptography/rsa/rsa.ipynb, qualtran/bloqs/cryptography/rsa/rsa_mod_exp.py
Use the functions docstring if using the `@bloq_example` annotation
=> Add BloqExample.docstring

dev_tools/requirements/deps/runtime.txt, dev_tools/requirements/envs/dev.env.txt, dev_tools/requirements/envs/docs.env.txt, dev_tools/requirements/envs/format.env.txt, dev_tools/requirements/envs/pylint.env.txt, dev_tools/requirements/envs/pytest.env.txt, dev_tools/requirements/envs/runtime.env.txt
Adds `pyzx` to the runtime dependencies. to unblock PRs towards #1517
=> Add dependency: `pyzx`

qualtran/cirq_interop/_bloq_to_cirq.py, qualtran/cirq_interop/_bloq_to_cirq_test.py
=> Fix BloqAsCirqGate.__pow__

dev_tools/requirements/envs/dev.env.txt, dev_tools/requirements/envs/docs.env.txt, dev_tools/requirements/envs/format.env.txt, dev_tools/requirements/envs/pylint.env.txt, dev_tools/requirements/envs/pytest.env.txt, dev_tools/requirements/envs/runtime.env.txt
regularly scheduled dependency bump
=> [2025-03] Bump dependencies

qualtran/bloqs/cryptography/ecc/ec_add_test.py, qualtran/bloqs/cryptography/ecc/find_ecc_private_key_test.py, qualtran/bloqs/cryptography/rsa/rsa_phase_estimate_test.py, qualtran/surface_code/beverland_et_al_model_test.py, qualtran/surface_code/physical_cost_model_test.py
So they don't get executed as part of the quick suite. They get tested by the dedicated notebook CI job
=> Mark notebook unit tests

qualtran/bloqs/chemistry/sparse/prepare.py
=> Fix expression for prepare.num_lt

dev_tools/requirements/deps/runtime.txt, dev_tools/requirements/envs/dev.env.txt, dev_tools/requirements/envs/docs.env.txt, dev_tools/requirements/envs/format.env.txt, dev_tools/requirements/envs/pylint.env.txt, dev_tools/requirements/envs/pytest.env.txt, dev_tools/requirements/envs/runtime.env.txt
=> Add Pennylane to dependencies for interop

setup.py
needed for pypi to accept our package
=> [v0.6 branch] long_description_content_type='text/markdown' in setup.py

dev_tools/requirements/envs/dev.env.txt, dev_tools/requirements/envs/docs.env.txt, dev_tools/requirements/envs/format.env.txt, dev_tools/requirements/envs/mypy.env.txt, dev_tools/requirements/envs/pip-tools.env.txt, dev_tools/requirements/envs/pylint.env.txt, dev_tools/requirements/envs/pytest.env.txt, dev_tools/requirements/envs/runtime.env.txt
Regularly scheduled dependency updates
=> 2025-08 Bump dependencies

dev_tools/qualtran_dev_tools/notebook_specs.py, qualtran/bloqs/gf_arithmetic/__init__.py, qualtran/bloqs/gf_arithmetic/gf2_multiplication.ipynb, qualtran/bloqs/gf_arithmetic/gf2_multiplication.py, qualtran/bloqs/gf_arithmetic/gf2_multiplication_test.py
`synthesize_reduction_matrix_q` has cost $m^2$ while `GF2ShiftRight(qgf, m)` has cost $m * w$ where `w` is the number of nonzero terms in the irreducible polynomial.
=> replace synthesize_reduction_matrix_q with GF2ShiftRight in GF2Multipication

dev_tools/qualtran_dev_tools/notebook_execution.py, docs/bloq_infra.rst, tutorials/quantum-programming/1-wiring-up.ipynb, tutorials/quantum-programming/2-bloqs.ipynb, tutorials/quantum-programming/3-addressing-bits.ipynb
Instead of one big tutorial on authoring bloqs, split it into one per concept (and do a better job of describing the concepts).
=> Tutorial notebooks

dev_tools/README.md, dev_tools/pyproject.toml
there are niche use cases for this. I also took the opportunity to briefly document the other contents of `dev_tools/`
=> Make qualtran_dev_tools installable

dev_tools/qualtran_dev_tools/notebook_specs.py, docs/bloqs/index.rst, qualtran/bloqs/hamiltonian_simulation/__init__.py, qualtran/bloqs/hamiltonian_simulation/guided_hamiltonian.ipynb, qualtran/bloqs/hamiltonian_simulation/guided_hamiltonian.py, qualtran/bloqs/hamiltonian_simulation/guided_hamiltonian_test.py, qualtran/bloqs/hamiltonian_simulation/tutorial_guided_hamiltonian.ipynb, qualtran/bloqs/qubitization/qubitization_walk_operator.py, qualtran/conftest.py, qualtran/serialization/resolver_dict.py
Implement the algorithm from Sec 4.2 of https://arxiv.org/abs/2406.19378v1
=> Add bloq for the Guided Hamiltonian Problem
