qualtran/_infra/composite_bloq.py
qualtran/bloqs/swap_network_cirq_test.py
qualtran/cirq_interop/_cirq_interop.py
qualtran/cirq_interop/_cirq_interop_test.py

This gets rid of the conversion to/from a flat list of API when wrapping a Bloq as a Cirq gate. Part of a larger series of PRs to improve Cirq interop. 
cc @mpharrigan

Use Cirq-FT's multi-dimensional registers directly in BloqAsCirqGate

---

qualtran/cirq_interop/_cirq_interop.py
qualtran/cirq_interop/_cirq_interop_test.py
qualtran/cirq_interop/cirq_interop.ipynb
qualtran/drawing/graphviz.py

This PR improves the `CirqGateAsBloq` such that now we can
- wrap Cirq-FT's `GateWithRegisters` without loosing the multi-dimensional register information
- Fallback on `cirq.decompose_once` to decompose the corresponding `CirqGateAsBloq`. 
- Any ancillas introduced in the decomposition are represented as explicit allocation/ deallocation nodes in the resulting composite graph (see example below for prepare hubbard)
These improvements will now enable importing all the nice primitives written in Cirq-FT with minimal overhead, so that they can be used directly as Bloqs. The modified notebook shows example code for importing the SELECT and PREARE circuits for 2D Hubbard Model as Bloqs using `CirqGateAsBloq`. Also see the following examples
The diagrams below is for a scaled down version …

Support cirq registers in `CirqGateAsBloq` conversion

---

qualtran/bloqs/basic_gates/rotation.py

Add bloq counts for rotations.

---

dev_tools/requirements/deps/runtime.txt
dev_tools/requirements/envs/dev.env.txt
dev_tools/requirements/envs/docs.env.txt
dev_tools/requirements/envs/format.env.txt
dev_tools/requirements/envs/pylint.env.txt
dev_tools/requirements/envs/pytest.env.txt
dev_tools/requirements/envs/runtime.env.txt

#389 and #388 lead to quantumlib/cirq#6313 and quantumlib/cirq#6312. I need to bump the cirq version to incorporate these fixes to unblock #350.

Bump cirq version for arithmetic #6313 and #6312.

---

qualtran/bloqs/apply_gate_to_lth_target.ipynb
qualtran/bloqs/apply_gate_to_lth_target.py
qualtran/bloqs/apply_gate_to_lth_target_test.py
qualtran/cirq_interop/jupyter_tools.py
qualtran/cirq_interop/jupyter_tools_test.py

Add `ApplyGateToLthQubit` Bloq from Cirq-FT

---

qualtran/bloqs/multi_control_multi_target_pauli.py
qualtran/bloqs/multi_control_multi_target_pauli_test.py

Add MCMT Pauli Bloqs from Cirq-FT

---

qualtran/__init__.py
qualtran/_infra/bloq.py
qualtran/_infra/bloq_example.py
qualtran/_infra/bloq_example_test.py
qualtran/cirq_interop/_cirq_to_bloq.py
qualtran/cirq_interop/_cirq_to_bloq_test.py
qualtran/conftest.py
qualtran/drawing/graphviz_test.py
qualtran/testing.py
qualtran/testing_test.py

- `BloqExample` for encapsulating instantiations of bloqs on which we can perform tests (and eventually: document). Consider this an extension of the `_make_xx()` functions currently used in `dev_tools/autogenerate-bloqs-notebooks.py`. Follow-on work will port all these make functions and the autodoc infrastructure to use `BloqExample`.
- "check" functions that return not only "pass" or "fail" but also "na", "missing", or "unverified" to form the basis of a bloq "report card": a matrix of bloq examples on one axis and checks on the other
- wrap the check functions in a `pytest` fixture so all the checks can be run on a given bloq example, simplifying running unit tests. Just like the notebook checks: I imagine that each bloq will have a unit test that runs the checks on that bloq for …

[autotest] Basic structure for automatic testing

---

qualtran/cirq_interop/_cirq_to_bloq.py
qualtran/cirq_interop/_cirq_to_bloq_test.py

Fixes https://github.com/quantumlib/Qualtran/pull/350#discussion_r1362789784
A recent PR updated the error raising and handling logic where `bloq.decompose_bloq()` should raise a `DecomposeNotImplementedError` if there doesn't exist a valid decomposition. `CirqGateAsBloq` was still raising a `ValueError` in some of these cases. This PR updates the logic and thus fixes the bug mentioned in above conversation.

`CirqGateAsBloq` should raise `DecomposeNotImplementedError` if underlying gate does not have a decomposition

---

qualtran/bloqs/qrom.py
qualtran/bloqs/qrom_test.py
qualtran/bloqs/select_swap_qrom.py
qualtran/bloqs/select_swap_qrom_test.py

This PR also updates the signature method of `QROM` to make sure we don't instantiate a register of bitsize 0. Going forward, we should raise an error from constructor of `Signature` if any register of `bitsize 0` is provided.

Add `SelectSwapQROM` Bloq from Cirq-FT

---

qualtran/bloqs/mean_estimation/__init__.py
qualtran/bloqs/mean_estimation/arctan.py
qualtran/bloqs/mean_estimation/arctan_test.py
qualtran/bloqs/mean_estimation/complex_phase_oracle.py
qualtran/bloqs/mean_estimation/complex_phase_oracle_test.py
qualtran/bloqs/mean_estimation/mean_estimation_operator.py
qualtran/bloqs/mean_estimation/mean_estimation_operator_test.py

Mostly a copy / paste. Moves all mean estimation code from Cirq-FT to Qualtran.

Move mean estimation code from Cirq-FT to Qualtran

---

dev_tools/autogenerate-bloqs-notebooks-v2.py
dev_tools/qualtran_dev_tools/cirq_ft_jupyter_autogen_factories.py
dev_tools/qualtran_dev_tools/jupyter_autogen.py
qualtran/bloqs/apply_gate_to_lth_target.ipynb
qualtran/bloqs/apply_gate_to_lth_target.py
qualtran/bloqs/apply_gate_to_lth_target_test.py
qualtran/bloqs/factoring/mod_exp.ipynb
qualtran/bloqs/factoring/mod_mul.ipynb
qualtran/bloqs/swap_network_2.ipynb

Port the example for `ApplyGateToLthQubit` from old-style to new-style.
As always: the jupyter autogen will leave user-authored cells unaffected; so I kept the cirqy decomposition view

[autodoc/autotest] ApplyGateToLthQubit

---

qualtran/surface_code/algorithm_summary.py
qualtran/surface_code/algorithm_summary_test.py
qualtran/surface_code/rotation_cost_model.py
qualtran/surface_code/rotation_cost_model_test.py

This abstraction covers both standarad models which have a cost of $A \log_2(1/\epsilon) + B$ Where $A$ 
and $B$ depend on the gateset, approximation protocol and hardware parameters and are obtained by fitting regression models. It also covers models with constant per rotation of cost which require a circuit that gets prepared once which gives preparation overhead.
I'm reporting the cost as an `AlgorithmSummary` object rather than a `TComplexity` object because it's more natural to report the cost of the second model in terms of Toffoli count rather than T count.
Related to https://github.com/quantumlib/Qualtran/issues/370 and is part of https://github.com/quantumlib/Qualtran/issues/269

Add rotation cost model

---

qualtran/_infra/gate_with_registers.py
qualtran/bloqs/arithmetic.py
qualtran/bloqs/arithmetic_test.py
qualtran/bloqs/chemistry/trotter/potential.py
qualtran/cirq_interop/testing.py

Adds an implementation and tests for `OutOfPlaceAdder` described in Figure 4b of https://arxiv.org/abs/1709.06648
Makes the following drive by changes
1. Changes signature of `OutOfPlaceAdder` such that the output register `c` is a newly allocated RIGHT (or LEFT for adjoint) register of size `bitsize+1`. Uncomputing the `c` register now takes 0 T-gates.
2. Fixes a bug in `PairPotential` where the register `c` was not getting uncomputed. There are potentially still more bugs in this implementation. See https://github.com/quantumlib/Qualtran/issues/482
3. Improves `assert_decompose_is_consistent_with_t_complexity` so that it checks for both `_t_complexity_` and `t_complexity` methods because `GateWithRegisters` is now `Bloq`. We can eventually get rid of `_t_complexity_` completely.
4. Adds …

Add implementation of Gidney's `OutOfPlaceAdder` and use optimized `TComplexity`

---

qualtran/_infra/bloq_test.py
qualtran/_infra/composite_bloq_test.py
qualtran/_infra/gate_with_registers.py
qualtran/_infra/registers.py
qualtran/_infra/registers_test.py
qualtran/bloqs/basic_gates/rotation_test.py
qualtran/bloqs/swap_network.py
qualtran/cirq_interop/__init__.py
qualtran/cirq_interop/_bloq_to_cirq.py
qualtran/cirq_interop/_bloq_to_cirq_test.py
qualtran/cirq_interop/_cirq_to_bloq.py
qualtran/cirq_interop/_cirq_to_bloq_test.py
qualtran/cirq_interop/cirq_interop.ipynb

Makes a bunch of simplifications to the `cirq_interop` directory, makes `GateWithRegisters` implementation more robust and removes legacy code after Cirq-FT / Qualtran code integration is completed. 
Fixes https://github.com/quantumlib/Qualtran/issues/398
The only thing left after this PR is documentation improvements for `GateWithRegisters`, `CirqGateAsBloq` and `BloqAsCirqGate`.

Cleanup Cirq interop after Cirq-FT / Qualtran integration

---

qualtran/bloqs/basic_gates/__init__.py
qualtran/bloqs/basic_gates/rotation.py
qualtran/bloqs/basic_gates/rotation_test.py
qualtran/bloqs/chemistry/thc/prepare.py
qualtran/bloqs/chemistry/thc/select.py
qualtran/bloqs/chemistry/trotter/qvr.py
qualtran/bloqs/chemistry/trotter/trotter.ipynb
qualtran/cirq_interop/__init__.py
qualtran/cirq_interop/_cirq_to_bloq.py
qualtran/cirq_interop/_cirq_to_bloq_test.py

This PR does a bunch of changes/improvements in cirq interop
- Introduces a new `CirqGateAsBloqBase` abstract class which has all the functionality to auto populate the bloq methods using underlying Cirq gates. There is one abstract method called `cirq_gate` which can be over-riden by derived classes. 
- The wrapper class `CirqGateAsBloq` simply derives from `CirqGateAsBloqBase` and uses the user specified `self.gate` as the corresponding `cirq_gate`.
- However, users can now also derive from `CirqGateAsBloqBase` class and specify a custom cirq gate as the `cirq_gate` property. For commonly used gates in Cirq-Core, this inheritance based method for wrapping cirq gates solves the discoverability issue and reduces boilerplace code. 
- This is now used in the `rotations.py` file to wrap `Rx …

Add `XPow/YPow/ZPow` rotations gate

---

dev_tools/requirements/deps/dev-tools.txt
dev_tools/requirements/envs/dev.env.txt
dev_tools/requirements/envs/docs.env.txt
dev_tools/requirements/envs/format.env.txt
dev_tools/requirements/envs/pylint.env.txt
dev_tools/requirements/envs/pytest.env.txt
dev_tools/requirements/envs/runtime.env.txt

Not sure if this is a recent change, but I noticed `jupyter notebook` doesn't work in a fresh dev environment. I consider it to be a vital component of a standard dev environment.

Make sure jupyter notebook is installed in a dev environment.

---

check/pytest-and-incremental-coverage
check/pytest-changed-files
check/pytest-changed-files-and-incremental-coverage

As file `dev_tools/pypath` does not exist.

delete `source dev_tools/pypath` in check scripts

---

dev_tools/qualtran_dev_tools/clean_notebooks.py

In #190 I had switched from `jq` to first-party `nbconvert` which has metadata and outputs as two different things one can clear. This didn't show up in my testing since we're actually good about clearing outputs from our committed notebooks :)

Fixup clean_notebooks.py

---

qualtran/bloqs/basic_gates/swap.py

I think there's a more general issue with `wire_symbol_from_gate` in GateWithRegisters (I'll open an issue / take a look), but for sure the CSwap was diagram was not being constructed properly.
Before:
After:

Fix CSwap wiresymbols.

---

qualtran/drawing/musical_score.py

Don't draw axis by default in musical score figures

---

qualtran/_infra/bloq_test.py
qualtran/_infra/composite_bloq.ipynb
qualtran/_infra/composite_bloq_test.py
qualtran/_infra/quantum_graph_test.py
qualtran/bloqs/controlled_bloq_test.py
qualtran/bloqs/for_testing/__init__.py
qualtran/bloqs/for_testing/atom.py
qualtran/bloqs/for_testing/atom_test.py
qualtran/bloqs/for_testing/many_registers.py
qualtran/bloqs/for_testing/many_registers_test.py
qualtran/bloqs/for_testing/with_decomposition.py
qualtran/bloqs/for_testing/with_decomposition_test.py
qualtran/bloqs/util_bloqs.ipynb
qualtran/bloqs/util_bloqs_test.py
qualtran/drawing/graphviz.ipynb
qualtran/drawing/graphviz_test.py
qualtran/serialization/bloq.py
qualtran/serialization/bloq_test.py
qualtran/testing_test.py

There's been a bunch of ad hoc bloqs in various `*_test.py` files. This PR tries to consolodate some of that into `qualtran.bloqs.for_testing`. Whereas other bloqs in the standard library can and will evolve and have their features change -- theses should be used to test qualtran infra and protocols where a unit test wants to make sure things work on a minimal, generic, unchanging bloq.
This includes one- and two- bit atomic (leaf/non-decomposable) bloqs; two bloqs with decompositions in serial and parallel configuration; and the many-register ("complicatedbloq") from the block encoding tests. 
This PR changes the tests and notebooks to use these centralized generic bloqs.
When a specific bloq property is required for a unit test, we leave those bloqs as defined inside the `_test.py` …

Factor out generic bloqs for testing

---

qualtran/bloqs/arithmetic/addition.py
qualtran/bloqs/arithmetic/addition_test.py

I needed to reverse the qubit order in the cirq decomposition to ensure big-endianness was preserved (the giveaway was the original unit test was reversing the iter_bits list of bits).

Fixes bug with addition endianness.

---

qualtran/_infra/bloq.py
qualtran/bloqs/basic_gates/swap_test.py
qualtran/bloqs/chemistry/thc/notebook_utils.py
qualtran/bloqs/chemistry/thc/prepare_test.py
qualtran/bloqs/swap_network_test.py
qualtran/resource_counting/__init__.py
qualtran/resource_counting/bloq_counts.py
qualtran/resource_counting/generalizers.py
qualtran/resource_counting/generalizers_test.py

When we're computing call graphs, we can "generalize" bloqs: ignore some or lump others together. This PR provides a library of off-the-shelf generator functions and now supports passing in multiple such functions to the public api.
- Add a type annotation for the generalizer callable interface
- helper function to turn many generalizers into one generalizer that calls each of them
- which is used by the new public api: can provide a sequence of generalizers
- generalizers module contains common generalizer functions
- use these common functions elsewhere in the library instead of always re-implementing them

An assortment of generalizers

---

qualtran/bloqs/basic_gates/swap.py
qualtran/bloqs/chemistry/black_boxes.py
qualtran/bloqs/chemistry/df/double_factorization.ipynb
qualtran/bloqs/chemistry/df/double_factorization.py
qualtran/bloqs/chemistry/df/prepare.py
qualtran/bloqs/chemistry/df/prepare_test.py
qualtran/bloqs/chemistry/df/select_bloq.py
qualtran/bloqs/chemistry/df/select_bloq_test.py
qualtran/bloqs/chemistry/resource_estimation.ipynb
qualtran/bloqs/chemistry/sf/prepare.py
qualtran/bloqs/chemistry/sf/prepare_test.py
qualtran/bloqs/chemistry/sf/single_factorization.py
qualtran/bloqs/chemistry/thc/prepare.py

Following #566 
- CSwap is self-adjoint
- QROAM stub keeps its (renamed) flag for accurate costing / keeping this PR from being too complicated
- All other `adjoint` boolean in the chemistry bloqs are superfluous

More idiomatic adjoint changes

---

dev_tools/requirements/deps/runtime.txt
dev_tools/requirements/envs/dev.env.txt
dev_tools/requirements/envs/docs.env.txt
dev_tools/requirements/envs/format.env.txt
dev_tools/requirements/envs/pip-tools.env.txt
dev_tools/requirements/envs/pylint.env.txt
dev_tools/requirements/envs/pytest.env.txt
dev_tools/requirements/envs/runtime.env.txt

- pydot has a major version bump, but the changelog looks fine
- quimb looks like it changed its preferred backend which is now declared in its dependencies rather than us listing a bunch of things ourselves.

Bump dependencies

---

qualtran/bloqs/rotations/phase_gradient_test.py
qualtran/bloqs/util_bloqs.py
qualtran/bloqs/util_bloqs_test.py

An `Allocate` bloq should correspond to a new n-bit `|0^{n}>` state. 
Partially fixes https://github.com/quantumlib/Qualtran/issues/616 (adjoint uses `Free` which still doesn't have a tensor decomposition)
Obsoletes https://github.com/quantumlib/Qualtran/pull/615
Part of resolving https://github.com/quantumlib/Qualtran/issues/513

Add `add_my_tensors` implementation to Allocate and enable tensor contraction for `PhaseGradientState` Bloq

---

qualtran/bloqs/rotations/phase_gradient_test.py
qualtran/bloqs/util_bloqs.py
qualtran/bloqs/util_bloqs_test.py

Continuation of https://github.com/quantumlib/Qualtran/pull/617
Fixes #616 
Fixes #513 
Obsoletes https://github.com/quantumlib/Qualtran/pull/615

Add `add_my_tensors` implementation to `Free` and enable tensor contraction for `PhaseGradientState` adjoint Bloq

---

qualtran/bloqs/basic_gates/toffoli.py
qualtran/bloqs/basic_gates/x_basis.py
qualtran/drawing/_show_funcs.py
qualtran/drawing/musical_score.py

- Fix the aspect ratio of the figure so that circles show up as circles.
- Fix figure sizing so it can be as small as possible but then maxes out at a given size, but keep the aspect ratio correct
- `show_bloq` can now `show_bloq(bloq, type='musical_score')` 
This is pulled out of #600 . I visually tested the figure sizing there, as it was easy to make arbitrary width, depth circuits with circular symbols.

Improve musical score drawing

---

qualtran/bloqs/chemistry/thc/prepare.py

Similar to #612 I want to move towards not using the [black box bloqs](https://github.com/quantumlib/Qualtran/blob/main/qualtran/bloqs/chemistry/black_boxes.py#L113) when we have something similar in Qualtran. No tests had to be modified as the costs are currently not compared to openfermion except in the notebook.
It's a little harder to remove the QROAM bloq everywhere as it would require the Hamiltonian specific data to be generated and used for SF and DF (see: #573). I don't see this as super high priority at this point -- but is something I plan to do.

Don't use black box QROAM in THC call graph.

---

qualtran/bloqs/generalized_qsp.py
qualtran/bloqs/generalized_qsp_test.py

Fixes issue in precision for real polynomials. The thetas seem robust to error, but not phis, as adding a small imaginary part can result in non zero angles. More discussion in #630.

[GQSP] fix bug in phase angle calculation

---

qualtran/_infra/registers.py
qualtran/_infra/registers_test.py

The ci is failing in #639 due to the comparator in the [unit test having zero bitsize](https://github.com/quantumlib/Qualtran/actions/runs/7805172959/job/21288750016#step:6:786). I'm not sure what our desired behavior is for registers of size zero, but the test previously passed  because signature.build would silently drop registers of size zero. I thought adding a similar method for dtypes would be helpful in this regard, which is implemented here, but it raises the question if we really want zero bitsize registers or should this just throw an error when constructing the type. I also thought it could be nice to handle the boilerplate of converting a QInt(1) to a QBit() but currently this will raise an ValueError during construction of QInt(1), so:
1. Should QDType(0) raise an error? I …

[data types] Add signature factory method build_from_dtypes

---

qualtran/_infra/data_types.py
qualtran/_infra/data_types_test.py
qualtran/bloqs/arithmetic/multiplication.py
qualtran/bloqs/arithmetic/multiplication_test.py
qualtran/bloqs/rotations/hamming_weight_phasing.py
qualtran/bloqs/rotations/hamming_weight_phasing_test.py
qualtran/bloqs/rotations/phase_gradient.py
qualtran/bloqs/rotations/phase_gradient_test.py
qualtran/bloqs/rotations/phasing_via_cost_function.py
qualtran/bloqs/rotations/phasing_via_cost_function_test.py

This PR introduces Bloqs and a generalized framework to implement oracles for phasing by a cost function as described in Section-3 of https://arxiv.org/abs/2007.07391. Specifically, the PR introduces the following changes:
* `PhasingViaCostFunction` : New Bloq that expects (a) $O_{\text{direct}}$ - cost function function evaluation oracle and (b) $O_{\text{phase}}$ - phasing oracle.  This bloq implements the general unitary 
$$
U_f(\gamma) = \sum_{x=0}^{N-1} e^{i 2 \pi \gamma f(x)} |x\rangle \langle x| 
$$
using 
$$
U_f(\gamma) = O_{\text{direct}}^{\dagger} O_{\text{phase}}(\gamma) O_{\text{direct}}
$$
where
$$
O_{\text{direct}}|x\rangle |0\rangle^{\otimes b_{\text{dir}}}  = |x\rangle |f(x)\rangle
$$
$$
O_{phase}(\gamma) |x\rangle |f(x)\rangle = e^{i 2 \pi \gamma f(x)} |x\rangle …

Bloqs for phasing by a cost function via addition into phase gradient register

---

qualtran/_infra/data_types.py
qualtran/_infra/data_types_test.py
qualtran/bloqs/arithmetic/addition.py
qualtran/bloqs/arithmetic/addition_test.py
qualtran/bloqs/basic_gates/cnot_test.py
qualtran/bloqs/basic_gates/x_basis_test.py
qualtran/bloqs/basic_gates/z_basis_test.py
qualtran/bloqs/util_bloqs_test.py
qualtran/simulation/classical_sim.py
qualtran/simulation/classical_sim_test.py

Move classical simulation datatype validation logic to the new data types #446 
Fix the `Add` bloq classical simulation if we were to support signed integers. re #607 for `Add`. Are there others @fpapa250 ?
helper functions to generate (and test) classical truth tables. This was helpful for eyeballing that e.g. Add was adding for all the values in the domain of the inputs. Data types can yield their value set (i.e. domain). 
I left some of the new methods for follow-up work, and some of the old classical validation tests are out-of-date until the bloqs under test learn their correct data types. I made a note that we may want an additional method in the future that turns classical values to 0-based indices to help writing tensors.

Classical simulation with data types 1

---

qualtran/bloqs/apply_gate_to_lth_target.py
qualtran/bloqs/hubbard_model.py
qualtran/bloqs/mean_estimation/complex_phase_oracle.py
qualtran/bloqs/mean_estimation/complex_phase_oracle_test.py
qualtran/bloqs/mean_estimation/mean_estimation_operator.py
qualtran/bloqs/mean_estimation/mean_estimation_operator_test.py
qualtran/bloqs/prepare_uniform_superposition.py
qualtran/bloqs/programmable_rotation_gate_array.py
qualtran/bloqs/programmable_rotation_gate_array_test.py
qualtran/bloqs/qrom.py
qualtran/bloqs/qubitization_walk_operator.py
qualtran/bloqs/reflection_using_prepare.py
qualtran/bloqs/select_and_prepare.py
qualtran/bloqs/select_pauli_lcu.py
qualtran/bloqs/select_swap_qrom.py
qualtran/bloqs/selected_majorana_fermion.py
qualtran/bloqs/state_preparation/state_preparation_alias_sampling.py
qualtran/bloqs/unary_iteration_bloq.py
qualtran/bloqs/unary_iteration_bloq_test.py
qualtran/cirq_interop/testing.py

Use functools.cached_property (instead of cirq)

---

dev_tools/requirements/deps/runtime.txt
dev_tools/requirements/envs/dev.env.txt
dev_tools/requirements/envs/docs.env.txt
dev_tools/requirements/envs/format.env.txt
dev_tools/requirements/envs/pip-tools.env.txt
dev_tools/requirements/envs/pylint.env.txt
dev_tools/requirements/envs/pytest.env.txt
dev_tools/requirements/envs/runtime.env.txt
qualtran/bloqs/unary_iteration.ipynb
qualtran/cirq_interop/t_complexity_protocol.py

The latest feature is the new and improved `cirq.has_stabilizer_effect` protocol which works for arbitrary unitaries acting on <= 3 qubits (and gates / bloqs that decompose into such unitaries). 
The reason I need to modify the T-complexity protocol to include the check `cirq.num_qubits(stc) <= 2` is that right now, the T-complexity numbers count only 1/2q clifford gates as valid cliffords. As a result, t-compleixty tests start failing for gates like `MultiTargetCNOT` which can be an n-qubit gate but decomposes into a bunch of cliffords (sequence of CNOTs) so would have a lower T-complexity if we allow counting > 2q cliffords as a single clifford in our costs. 
We can revisit the strategy to count cliffords later.

Update Cirq dependency to latest pre-release version

---

qualtran/bloqs/multi_control_multi_target_pauli.py
qualtran/bloqs/multi_control_multi_target_pauli_test.py

Fixes https://github.com/quantumlib/Qualtran/issues/677
cc [brempfer](https://github.com/brempfer)
Tests will start passing once https://github.com/quantumlib/Qualtran/pull/680 is merged because all controlled paulis are cliffords and the new `cirq.has_stabilizer_effect` implementation recognizes that.

Support 0 and 1 controls in `MultiControlPauli` Bloq

---

qualtran/bloqs/basic_gates/rotation_test.py
qualtran/cirq_interop/_cirq_to_bloq.py

Moves the `pretty_name()` override from `CirqGateAsBloqBase` to `CirqGateAsBloq` so that all explicitly defined Bloqs in Qualtran that derive from `CirqGateAsBloqBase` base class have their pretty name equal to their class name in Qualtran. This helps us more easily track the places in call graph where we yield the `cirq.<gate>` style gates vs where we directly use bloqs defined in Qualtran (which is preferable)

Delegate `pretty_name` to `cirq.<gate>` only for explicitly wrapped cirq gates in `CirqGateAsBloq` class

---

qualtran/_infra/bloq.py
qualtran/_infra/composite_bloq.py
qualtran/_infra/gate_with_registers.py
qualtran/bloqs/arithmetic/addition.py
qualtran/bloqs/arithmetic/comparison.py
qualtran/bloqs/arithmetic/conversions.py
qualtran/bloqs/arithmetic/multiplication.py
qualtran/bloqs/basic_gates/cnot.py
qualtran/bloqs/basic_gates/hadamard.py
qualtran/bloqs/basic_gates/rotation.py
qualtran/bloqs/basic_gates/rotation_test.py
qualtran/bloqs/basic_gates/swap.py
qualtran/bloqs/basic_gates/t_gate.py
qualtran/bloqs/basic_gates/toffoli.py
qualtran/bloqs/basic_gates/x_basis.py
qualtran/bloqs/basic_gates/z_basis.py
qualtran/bloqs/chemistry/trotter/inverse_sqrt.py
qualtran/bloqs/chemistry/trotter/qvr.py
qualtran/bloqs/factoring/mod_add.py
qualtran/bloqs/for_testing/atom.py
qualtran/bloqs/qft/qft_phase_gradient_test.py
qualtran/bloqs/rotations/hamming_weight_phasing_test.py
qualtran/bloqs/rotations/phase_gradient_test.py
qualtran/bloqs/sorting.py
qualtran/bloqs/util_bloqs.py
qualtran/cirq_interop/_cirq_to_bloq.py
qualtran/cirq_interop/t_complexity_protocol.py
qualtran/serialization/bloq_test.py

- switch to using cirq-style `t_complexity(x: Any)` strategies-based protocol for counting T gates
- Remove `Bloq.t_complexity()` overridable method. For convenience `Bloq.t_complexity` just forwards to the above function
- Add strategies for dealing with bloqs and compositebloqs
- Move rotations to `rotations=1` and a new method on `TComplexity` if you want an estimate for everything in terms of T instead of T+rotations. 
Fixes #662 
Fixes #489

Unify t-complexity protocol

---

qualtran/_infra/adjoint.py
qualtran/_infra/adjoint_test.py

Minor fix to help improve sigma output from callgraphs for Bloqs which have a custom `__str__` specified but auto generated `__repr__` from frozen attrs.

Override `__str__` of `Adjoint` to delegate to subloq's `__str__` instead of `__repr__`

---

qualtran/bloqs/rotations/phase_gradient_test.py
qualtran/bloqs/rotations/phasing_via_cost_function_test.py

Unit tests must be <2s and ideally <1s 
xref #711

Slow test marking

---

qualtran/cirq_interop/_bloq_to_cirq.py
qualtran/cirq_interop/_bloq_to_cirq_test.py

Currently using `CNOT` or `Toffoli` bloq's in a cirq circuit raises an error when you try to print the circuit
Adds `ModPlus` type to `_wire_symbol_to_cirq_diagram_info`. Also, @mpharrigan How do we keep the interop in sync with new `WireSymbol` classes? Should we add a text/pretty_str style property to `WireSymbol` class?

Fix failing circuit diagrams for Toffoli bloq when used in a Cirq circuit

---

qualtran/bloqs/basic_gates/__init__.py
qualtran/cirq_interop/t_complexity_protocol.py
qualtran/resource_counting/symbolic_counting_utils.py
qualtran/resource_counting/symbolic_counting_utils_test.py
qualtran/resource_counting/t_counts_from_sigma.py
qualtran/resource_counting/t_counts_from_sigma_test.py

After the recent change to T-complexity protocol https://github.com/quantumlib/Qualtran/pull/678/files, the correct way to extract T-counts for a Bloq is to process the bloq counts dictionary `sigma` obtained via `bloq.call_graph()`. 
This PR adds a helper that can process `sigma` and obtain the correct T-counts. This is a blocker for my analyses and can potentially be replaced by the upcoming generalized costs infrastructure. 
As part of this PR, I've also extracted the "utils" file, originally introduced in https://github.com/quantumlib/Qualtran/pull/688,  into `resource_counting/symbolic_counting_utils.py`.

Add `t_counts_from_sigma` helper to extract T-counts from

---

qualtran/_infra/adjoint.py
qualtran/_infra/adjoint_test.py

T-complexity protocol is important and currently broken. This PR temporarily unblocks development and analysis of algorithms using the T-complexity protocol (encountered in https://github.com/quantumlib/Qualtran/pull/732 ). 
See  https://github.com/quantumlib/Qualtran/issues/735 for a more detailed discussion to design the future of T-complexity.

Temporarily fix the failing T-Complexity for Adjoint

---

qualtran/_infra/adjoint.py
qualtran/_infra/adjoint_test.py
qualtran/_infra/bloq.py
qualtran/_infra/gate_with_registers.py
qualtran/cirq_interop/_bloq_to_cirq.py

Follow up of https://github.com/quantumlib/Qualtran/pull/736. See added tests for more bugfixes. 
One philosophical discussion - what's the difference between `DecomposeNotImplemented` and `DecomposeTypeErrror`? In Cirq, we just return `NotImplmented` if the decomposition is not implemented and I've updated the logic to map both the above errors to this behavior. 
@mpharrigan Can you check if this looks good?

More improvements and bugfixes to t-complexity protocol to make things work with Adjoint

---

qualtran/cirq_interop/t_complexity_protocol.py
qualtran/cirq_interop/t_complexity_protocol_test.py

Needed in https://github.com/quantumlib/Qualtran/pull/732
Larger discussion on improving T-complexity in https://github.com/quantumlib/Qualtran/issues/735
This is strictly better because bloqs `build_call_graph` can fallback to `decompose_bloq` if user doesn't have a custom `build_call_graph` specified. The latter is often faster and more commonly specified (eg: all newly added chemistry bloqs)

Use `build_call_graph` instead of `decompose_bloq` to compute `TComplexity`for bloqs

---

qualtran/cirq_interop/t_complexity_protocol.py
qualtran/cirq_interop/t_complexity_protocol_test.py

Recently added `_from_bloq_build_call_graph` strategy has a bug. If the bloq does not have a decomposition, there's no error raised and instead we get a `sigma` corresponding to `{stc : 1}`. 
This PR fixes the bug and adds a test for the same.

Fix infinite recursion bug in `t_complexity` protocol

---

dev_tools/autogenerate-bloqs-notebooks-v2.py
dev_tools/qualtran_dev_tools/cirq_ft_jupyter_autogen_factories.py
qualtran/bloqs/basic_gates/z_basis.py
qualtran/bloqs/qrom.ipynb
qualtran/bloqs/qrom.py
qualtran/bloqs/qrom_test.py
qualtran/bloqs/unary_iteration_bloq.py
qualtran/cirq_interop/_bloq_to_cirq.py
qualtran/drawing/musical_score.py
qualtran/simulation/classical_sim.py

Add classical simulation capabilities to QROM. This involves switching some of the `cirq.CNOT`s over. Add autodocs for QROM.

QROM - classical simulation and docs

---

qualtran/bloqs/arithmetic/hamming_weight.py
qualtran/bloqs/rotations/hamming_weight_phasing_test.py
qualtran/cirq_interop/testing.py

Fixes https://github.com/quantumlib/Qualtran/issues/762
Also adds a test to `assert_decompose_is_consistent_with_t_complexity` to verify the T-counts against `sigma` obtained via `bloq.build_call_graph`

Fix T-complexity obtained via `build_call_graph` for HWP and add automatic assertions

---

qualtran/bloqs/arithmetic/hamming_weight.py
qualtran/bloqs/arithmetic/hamming_weight_test.py

Fixes a TODO (see comment in code) and removes the special override for `adjoint` in `HammingWeightCompute`. 
The T-Complexity method is updated to accept a `adjoint` parameter and make the tests pass, but should be changed as part of https://github.com/quantumlib/Qualtran/issues/735

Remove special adjoint override of `HammingWeightCompute` Bloq

---

qualtran/_infra/registers.py
qualtran/_infra/registers_test.py

This is the minimum number of qubits a bloq must use for input and/or output. A bloq can use more if it allocates more qubits within itself. This is a helpful method for the qubit counting infrastructure.

Signature.n_qubits

---

qualtran/bloqs/chemistry/thc/prepare.py
qualtran/bloqs/mcmt/multi_control_multi_target_pauli.py
qualtran/bloqs/mcmt/multi_control_multi_target_pauli_test.py
qualtran/bloqs/reflection.py
qualtran/bloqs/reflection_using_prepare.py
qualtran/cirq_interop/t_complexity_protocol.py

This PR makes a bunch of improvements to `MultiControlPauli`, some of which are pulled out from https://github.com/quantumlib/Qualtran/pull/765
Specifically
1. `MultiControlPauli` learns classical simulation when target is an X gate
2. A more efficient tensor contraction which doesn't default to decomposing the Bloq; which is more expensive since it uses a bunch of ancilla qubits
3. Change the signature to accept a list of qubits instead of a single n-bit register as control

Improvements to `MultiControlPauli` 

---

qualtran/_infra/data_types.py
qualtran/_infra/data_types_test.py

This is useful to support classical and tensor simulations and support conversion of control values to Cirq. I'll demonstrate usage in follow-up PRs. 
cc @fdmalone

QDTypes learn `to_bits` and `from_bits`

---

qualtran/bloqs/basic_gates/t_gate.py
qualtran/bloqs/basic_gates/t_gate_test.py

`TGate(is_adjoint=True).as_cirq_op` should return `cirq.T ** -1` but currently returns `cirq.T`. This is bad an was discovered when playing with https://github.com/quantumlib/Qualtran/pull/803

Fix bug in `TGate.as_cirq_op` when `is_adjoint=True`

---

qualtran/_infra/gate_with_registers.py
qualtran/_infra/gate_with_registers_test.py
qualtran/bloqs/generalized_qsp_test.py
qualtran/bloqs/util_bloqs.py
qualtran/bloqs/util_bloqs_test.py
qualtran/cirq_interop/_bloq_to_cirq.py
qualtran/cirq_interop/_bloq_to_cirq_test.py
qualtran/cirq_interop/cirq_interop.ipynb
qualtran/serialization/resolver_dict.py

This is a step towards using the new `Controlled` bloq instead of `cirq.Controlled` gate throghout the library. Eventually, we'd to update all the call sites so that `GateWithRegisters.controlled` follows the same api as `Bloq.controlled` but as a step towards this direction; this PR ensures that we move away from using `cirq.Controlled` gate and always stay in Qualtran land. 
Note: This further regressed the CI time from ~17m to ~19m due to https://github.com/quantumlib/Qualtran/issues/793 and the fact that `Controlled` bloq is not a `GateWithRegisters`, it cannot use the underlying unitary even when it wraps a `GateWithRegisters` bloq, when doing cirq style simulations. Using the `Controlled` bloq in cirq-style simulations forces us to go via tensor contraction. Making it a …

`GateWithRegisters.controlled()` now returns `BloqAsCirqGate(Controlled())` instead of `cirq.Controlled` gate.

---

qualtran/protos/ctrl_spec.proto
qualtran/protos/ctrl_spec_pb2.py
qualtran/protos/ctrl_spec_pb2.pyi
qualtran/serialization/ctrl_spec.py
qualtran/serialization/ctrl_spec_test.py

We had updated `qdtype -> qdtypes` in `CtrlSpec` class but the change didn't propagate to the proto. This PR fixes that and adds tests.

Bugfix in `CtrlSpec` serialization

---

qualtran/_infra/data_types.py
qualtran/_infra/data_types_test.py
qualtran/drawing/graphviz.py

Fixes https://github.com/quantumlib/Qualtran/issues/855 and keeps up with the philosophy of https://github.com/quantumlib/Qualtran/issues/791 to use `__str__` for pretty and informative names

Add `__str__` to data types and use it in diagrams

---

docs/index.rst

The `:ref:` directive is supposed to pull the nice title from the refereced page's title, which works almost all the time. The pydata theme we're using has an "on this page" secondary navbar on the right that was pulling the key names, i.e. `bloq_infra`. This PR puts the full titles explicitly in the top-level `index.rst` which fixes the issue.

Explicit titles for top-level docs sections, workaround

---

qualtran/bloqs/reflection_using_prepare_test.py
qualtran/bloqs/state_preparation/state_preparation_alias_sampling_test.py

Mark tests as slow for state prep alias sampling and add a quick version. For reflection using prepare, reduce the range of tests.

Mark tests slow

---

qualtran/bloqs/chemistry/thc/thc.ipynb
qualtran/bloqs/hamiltonian_simulation/hamiltonian_simulation_by_gqsp.ipynb
qualtran/bloqs/mcmt/multi_control_multi_target_pauli.ipynb

Rerunning the autogen script results in this diff. I added flame graph imports directly above the call sites as the autogen function will just erase the import where was before. Maybe we should add an import for the flame_graph to the autodoc in the future?

Update stale notebooks.

---

qualtran/_infra/adjoint.py
qualtran/_infra/controlled.py
qualtran/_infra/controlled_test.py
qualtran/_infra/gate_with_registers.py
qualtran/_infra/gate_with_registers_test.py
qualtran/bloqs/phase_estimation/lp_resource_state.py
qualtran/bloqs/phase_estimation/text_book_qpe.py
qualtran/bloqs/qsp/generalized_qsp.py
qualtran/bloqs/qubitization_walk_operator_test.py
qualtran/bloqs/util_bloqs.py
qualtran/cirq_interop/_cirq_to_bloq.py
qualtran/cirq_interop/t_complexity_protocol.py

Fixes https://github.com/quantumlib/Qualtran/issues/865
Fixes https://github.com/quantumlib/Qualtran/issues/686
The improvements are -
- `GateWithRegisters.controlled()` now returns `Controlled` bloq
- `cirq_gate_to_bloq` now maps a `cirq.Controlled` gates to `Controlled` bloq.
- `Controlled` bloq is now a `GateWithRegisters`. This is required because we want to support cirq style simulations for circuits containing `Controlled(Rx())` bloqs and `BloqAsCirqGate(Controlled())` is not sufficient because we need special logic to derive the unitary matrix for controlled bloqs (eg: when subbloq is a GateWithRegisters but doesn't have only THRU registers). 
After this PR, we should never need to invoke the `cirq.Controlled` gates in either cirq-style or bloq-style API in Qualtran and we should …

More improvements to the Controlled infrastructure

---

qualtran/_infra/gate_with_registers.py
qualtran/_infra/gate_with_registers_test.py

Fixes https://github.com/quantumlib/Qualtran/issues/885
For now, I've mainly copied the logic from `cirq.ControlledGate` to construct `AbstractControlValues` object from parameters `num_controls`, `control_values` and `control_qid_shape` but we should eventually get rid of these arguments or at least move this to a different place instead of on `GateWithRegisters`. For example - we could add a new `GWROperation` for cirq-style API and delegate to underlying gate's `gwr.controlled(ctrl_spec)`. Right now, `cirq.GateOperation().controlled_by()` delegates to `gwr.controlled` but with the cirq-style API (`num_control`, `control_values`, `control_qid_shape`). 
cc @anurudhp

Remove unitary validation check when constructing `GateWithRegisters.controlled()`

---

check/pylint-changed-files

fixes this error:
```
************* Module dev_tools/conf/.pylintrc
dev_tools/conf/.pylintrc:1:0: W0012: Unknown option value for '--enable', expected a valid pylint message and got 'wrong-or-nonexistent-copyright-notice' (unknown-option-value)
************* Module Command line or configuration file
Command line or configuration file:1:0: E0013: Plugin 'pylint_copyright_checker' is impossible to load, is it installed ? ('No module named 'pylint_copyright_checker'') (bad-plugin-value)
```

`check/pylint-changed-files`: add `dev_tools/qualtran_dev_tools` to `PYTHONPATH`

---

qualtran/bloqs/basic_gates/su2_rotation.py
qualtran/bloqs/hamiltonian_simulation/hamiltonian_simulation_by_gqsp.ipynb
qualtran/bloqs/hamiltonian_simulation/hamiltonian_simulation_by_gqsp.py
qualtran/bloqs/hamiltonian_simulation/hamiltonian_simulation_by_gqsp_test.py
qualtran/bloqs/qsp/generalized_qsp.ipynb
qualtran/bloqs/qsp/generalized_qsp.py
qualtran/bloqs/qsp/generalized_qsp_test.py
qualtran/linalg/jacobi_anger_approximations.py
qualtran/resource_counting/symbolic_counting_utils.py
qualtran/resource_counting/symbolic_counting_utils_test.py

Discussion: https://github.com/quantumlib/Qualtran/issues/801

Symbolic `Shaped`

---

qualtran/bloqs/for_testing/matrix_gate.py
qualtran/bloqs/for_testing/matrix_gate_test.py
qualtran/bloqs/for_testing/random_select_and_prepare.py
qualtran/bloqs/hamiltonian_simulation/hamiltonian_simulation_by_gqsp_test.py
qualtran/bloqs/qsp/generalized_qsp_test.py
qualtran/serialization/resolver_dict.py

The name `RandomGate` doesn't make sense because we can instantiate with a matrix of choice as well.
This also renames `RandomGate.create(...)` -> `MatrixGate.random(...)` which makes more sense.
@mpharrigan @tanujkhattar PTAL

Rename `RandomGate` -> `MatrixGate`

---

qualtran/bloqs/basic_gates/global_phase.py
qualtran/cirq_interop/_cirq_to_bloq.py
qualtran/resource_counting/symbolic_counting_utils.py

The gate now supports symbolic phase coefficients.
The `_cirq_gate_to_bloq` was changed in #891 to only consider `float|complex`. This PR fixes the type in `GlobalPhase`, so that every `cirq.GlobalPhaseGate` can be converted to it.

Fix coefficient type for `GlobalPhase`, and convert from cirq correctly

---

qualtran/bloqs/arithmetic/multiplication.py
qualtran/bloqs/chemistry/quad_fermion/givens_bloq.py
qualtran/bloqs/chemistry/quad_fermion/givens_bloq_test.py
qualtran/bloqs/qft/approximate_qft.py
qualtran/bloqs/qft/approximate_qft_test.py
qualtran/bloqs/qft/qft_text_book.py
qualtran/bloqs/rotations/phase_gradient.py
qualtran/bloqs/rotations/phase_gradient_test.py

- Change controlled attribute to is_controlled or controlled_by.
- This attribute shadows the controlled() function inherited by GateWithRegisters which is confusing and type-unsafe.

Changed controlled attribute to is_controlled

---

qualtran/bloqs/basic_gates/toffoli_test.py
qualtran/testing.py

- Allow wire symbol testing to accept non-trivial shapes (multi-dimensional registers)
- Allow wire symbol testing to accept WireSymbols without text
- Add wire symbol testing to Toffoli()
Fixes: #608

Improve wire symbol testing

---

qualtran/_infra/gate_with_registers.py
qualtran/bloqs/for_testing/random_select_and_prepare.py
qualtran/bloqs/hubbard_model.py
qualtran/bloqs/hubbard_model_test.py
qualtran/bloqs/mean_estimation/mean_estimation_operator.py
qualtran/bloqs/mean_estimation/mean_estimation_operator_test.py
qualtran/bloqs/multiplexers/select_pauli_lcu.py
qualtran/bloqs/multiplexers/select_pauli_lcu_test.py
qualtran/bloqs/qubitization_walk_operator.py
qualtran/bloqs/qubitization_walk_operator_test.py
qualtran/bloqs/reflection_using_prepare.py
qualtran/bloqs/reflection_using_prepare_test.py

Fix custom controlled versions of `SelectOracle`s and `QubitizationWalkOperator`s

---

qualtran/bloqs/chemistry/sparse/sparse_test.py

#882 prematurely merged itself before the mypy check passed. Fix it here.

Fix chemistry mypy error

---

qualtran/bloqs/hamiltonian_simulation/hamiltonian_simulation_by_gqsp.py
qualtran/bloqs/hamiltonian_simulation/hamiltonian_simulation_by_gqsp_test.py
qualtran/bloqs/qubitization_walk_operator.py
qualtran/bloqs/qubitization_walk_operator_test.py

Fixes https://github.com/quantumlib/Qualtran/issues/936
Note that symbolic case reported in https://github.com/quantumlib/Qualtran/issues/935#issuecomment-2102719963 but that is now because of a niche sympy error. The core issue is that `big_O()` notation does not play well with "add up summations of individual terms" logic implemented in the T-complexity protocol. 
See the details below for the error raised when testing t-complexity for symbolic hamiltonian simulation via gqsp bloq
<details>
```
>       _ = symbolic_hamsim_by_gqsp.gqsp.t_complexity()
qualtran/bloqs/hamiltonian_simulation/hamiltonian_simulation_by_gqsp_test.py:103:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ …
```

Add explicit adjoint for qubitization walk operator

---

qualtran/bloqs/arithmetic/addition.py
qualtran/bloqs/arithmetic/comparison.py
qualtran/bloqs/basic_gates/hadamard.py
qualtran/bloqs/basic_gates/s_gate.py
qualtran/bloqs/basic_gates/su2_rotation.py
qualtran/bloqs/basic_gates/swap.py
qualtran/bloqs/basic_gates/t_gate.py
qualtran/bloqs/mod_arithmetic/_shims.py

- Removes superfluous and redundant textboxes from arithmetic and basic gates where the operation should be fairly obvious.

Remove title text boxes from arithmetic and basic gates

---

qualtran/_infra/composite_bloq.py
qualtran/_infra/controlled_test.py

Pass kwargs as kwargs, otherwise, an extra dictionary layer is added. Adds a test that exercises this.
Fixes: #955

Fix cirq_quregs argument in composite_bloq

---

qualtran/bloqs/hamiltonian_simulation/hamiltonian_simulation_by_gqsp.py
qualtran/bloqs/hamiltonian_simulation/hamiltonian_simulation_by_gqsp_test.py
qualtran/bloqs/hubbard_model.py
qualtran/bloqs/util_bloqs.py
qualtran/symbolics/math_funcs.py

- fixes the first bug reported in https://github.com/quantumlib/Qualtran/issues/935#issuecomment-2102719963 - adds a simplified override for the call graph of a symbolic HamSimbyGQSP bloq.
- introduces `_BookkeepingBloq` for utility bloqs that are used for book-keeping (i.e. cast, split/join, alloc/free)

Fix `t_complexity` for symbolic ham. sim. by gqsp example

---

qualtran/bloqs/arithmetic/addition.py
qualtran/bloqs/arithmetic/addition_test.py

- Handle bitwise overflow in addition plus k.
- All other arithmetic functions either handle overflow correctly or have enough bits in the output to avoid overflow.
Fixes: #607

Handle overflow in addition plus k classical function

---

qualtran/_infra/controlled.py

This is useful to visualize and analyze bloq decomposition diagrams where the decomposition may have multiple controlled-bloqs of the same subbloq but with different number of controls 
For example, 
is much more helpful than

Show number of controls in string representation of controlled bloq

---

qualtran/bloqs/swap_network/cswap_approx.py
qualtran/bloqs/swap_network/cswap_approx_test.py

- Part of #905.
- Removed _t_complexity_ calculation and moved to assert since this has a call_graph, the T count can be inferred.

Remove _t_complexity_ of CSwapApprox

---

qualtran/bloqs/arithmetic/comparison.py
qualtran/bloqs/arithmetic/comparison_test.py

Fixes https://github.com/quantumlib/Qualtran/issues/1010
Helps support symbolics and better resource counting for comparison gates. 
Edit: Also updated `LessThanEqual` gate.

Replace `_t_complexity_` with `build_call_graph` in comparison gates

---

qualtran/bloqs/mcmt/and_bloq.py
qualtran/bloqs/mcmt/and_bloq_test.py
qualtran/resource_counting/generalizers.py
qualtran/resource_counting/generalizers_test.py
qualtran/symbolics/__init__.py
qualtran/symbolics/types.py

Part of a larger effort to better support symbolic resource estimation across bloqs. I will update the `cvs` parameter on other bloqs in follow-up PRs.

Remove `_t_complexity_` on `MultiAnd` and support symbolic `cvs`

---

dev_tools/requirements/deps/runtime.txt
dev_tools/requirements/envs/dev.env.txt
dev_tools/requirements/envs/docs.env.txt
dev_tools/requirements/envs/format.env.txt
dev_tools/requirements/envs/pylint.env.txt
dev_tools/requirements/envs/pytest.env.txt
dev_tools/requirements/envs/runtime.env.txt

Cirq release v1.4 last night. This PR updates the cirq dependence to the latest stable release instead of a pre-release version.

Update cirq version to latest stable release of 1.4

---

qualtran/bloqs/chemistry/thc/thc.ipynb
qualtran/bloqs/data_loading/qrom_base.py
qualtran/bloqs/data_loading/select_swap_qrom.py
qualtran/bloqs/data_loading/select_swap_qrom_test.py
qualtran/bloqs/state_preparation/state_preparation_via_rotation.py

Fixes https://github.com/quantumlib/Qualtran/issues/1019
Also fixes a bug in computation of `find_optimal_log_block_size` which was being called with `selection_bitsize` instead of `target_bitsize`.

Fix SelectSwapQROM error when selection bitsize is 0

---

qualtran/bloqs/block_encoding/block_encoding_base.py

The correct definition of the signal state has $\ket{l}$ rather than $\ket{0}$.

Fix typo in signal state in BlockEncoding

---

qualtran/bloqs/block_encoding/block_encoding.ipynb

Simply running `python dev_tools/autogenerate-bloqs-notebooks-v2.py` after recent typo fix in https://github.com/quantumlib/Qualtran/pull/1027

Regenerate block encoding notebook after recent typo fix

---

dev_tools/requirements/deps/runtime.txt
dev_tools/requirements/envs/dev.env.txt
dev_tools/requirements/envs/docs.env.txt
dev_tools/requirements/envs/format.env.txt
dev_tools/requirements/envs/pylint.env.txt
dev_tools/requirements/envs/pytest.env.txt
dev_tools/requirements/envs/runtime.env.txt

Jupyter notebook isn't a hard dependency for using the library, but your experience will be severely limited without it. This adds jupyter notebook (i.e. `notebook`) to the runtime requirements. This means it will get installed by default if you `pip install qualtran`, since that will read `deps/runtime.txt`. 
You can see that the `dev.env.txt` doesn't change much since it was already included there, but the notebook dependencies get added to all the other environments.

Add jupyter notebook to runtime requirements

---

qualtran/_infra/controlled_test.py
qualtran/drawing/bloq_counts_graph.py
qualtran/drawing/graphviz.py

There is an issue when trying to draw diagrams with unicode symbols on windows. Even though graphviz defaults to utf-8, the `pydot` intermediary writes a temporary file with (what I presume to be) the platform default which is insufficient for unicode. Luckily, there is a parameter we can set to get utf-8 everywhere. 
This also removes a not-very helpful test that fails on windows because of insignificant differences in numpy datatypes.

Windows support - utf8 in graphviz

---

dev_tools/autogenerate-bloqs-notebooks-v2.py
docs/bloq_infra.rst
docs/bloqs/index.rst
qualtran/bloqs/bookkeeping/bookkeeping.ipynb
qualtran/bloqs/phase_estimation/lp_resource_state.ipynb

- pick up a couple of stale changes from bloqs autogen
- include new notebooks in the TOC
- document modular arithmetic bloqs in the modular arithmetic section. I have a sneaking suspicion that this change was done before and got reverted in a merge conflict resolution

2024-05 Docs upkeep

---

qualtran/_version.py
qualtran/bloqs/data_loading/qrom.py
qualtran/bloqs/data_loading/qrom_base.py
qualtran/bloqs/data_loading/select_swap_qrom.py
qualtran/bloqs/data_loading/select_swap_qrom_test.py

Two bugfixes:
1. Use `self.use_dirty_ancilla` in `_value_equality_values_` -- This is important to make sure `bloq.t_complexity()` returns different values when `bloq` is initialized with `use_dirty_ancilla=True` vs `use_dirty_ancilla=False`. Right now, they can return the same value because the t-complexity is cached
2. `qrom_batched_target[0]` can return a numpy array because the target shapes can be multi-dimensional. This is especially true when input data is multi-dimensional (i.e. `data[N][M] --> bached_qrom_data[N / k1][M / k2]`). We need the `target_0_0_..._0`'th register and not the `target_0`th register; which can be multidimensional. 
The added tests fail on main but pass with this PR.

BugFix in `SelectSwapQROM` when multiple datasets are specified

---

qualtran/bloqs/data_loading/qrom_base.py

was previously used by `cirq.value_equality` which was removed in #1049 
@tanujkhattar ptal

remove unused `_value_equality_values_`

---

qualtran/_infra/bloq.py
qualtran/resource_counting/_call_graph.py
qualtran/resource_counting/_call_graph_test.py

Get bloq counts directly without going via the call graph. This can massively speed up `qlt_testing.assert_equivalent_bloq_counts`, which will necessarily call `CompositeBloq.bloq_counts` which will involve lots of hashing of the composite bloq xref #1073 .
This also has prompted me to finally deal with what happens if you have two of the same bloq in your list of BloqCountT, perhaps returned by `build_call_graph`. Indeed, bloq_counts returns a dictionary so we have to add those keys. This was also necessary to make sure that if two things get generalized to the same result, their counts get added into one entry. Dealing with this is a pre-requisite for #845

More direct bloq_counts()

---

qualtran/bloqs/bookkeeping/cast.py
qualtran/bloqs/bookkeeping/cast_test.py

fixes https://github.com/quantumlib/Qualtran/issues/734
blocking https://github.com/quantumlib/Qualtran/pull/1057

Implement classical action of Cast bloq

---

qualtran/bloqs/data_loading/qrom.py
qualtran/bloqs/data_loading/select_swap_qrom.py
qualtran/bloqs/swap_network/swap_with_zero.py
qualtran/symbolics/math_funcs.py
qualtran/symbolics/types.py

Prior to this change, `symbolics.prod` only accepted `SymbolicInt` arguments and returned `SymbolicInt`. Now, it also accepts `SymbolicFloat` to return `SymbolicFloat`.
The function also now accepts an iterator rather than being variadic, matching the interface of built-in `sum`.
This goal is achieved via a new type variable `SymbolicT`. There does not seem to be a correct approach using `@overload` instead due to limitations of mypy, which does not consider `float | Expr` and `int | Expr` to be two valid overloads for a function since `int` is automatically promoted to `float`.

Generalize `symbolics.prod` to allow `SymbolicFloat` or `SymbolicInt`

---

qualtran/bloqs/mcmt/multi_control_multi_target_pauli.py
qualtran/cirq_interop/__init__.py
qualtran/cirq_interop/_cirq_to_bloq.py
qualtran/cirq_interop/t_complexity_protocol.py
qualtran/resource_counting/generalizers.py

This is generally useful when switching between Cirq gates and bloqs that are basic gates; part of #1109

Make `cirq_gate_as_bloq` public

---

qualtran/bloqs/block_encoding/linear_combination_test.py

These tests are slower but are intended to give more confidence for correctness.
We generate 10 tests, each adding 3 to 6 random block encodings of bitsize 1 to 3 with random coefficients between -10 and 10.

Add random tests for `LinearCombination`

---

qualtran/bloqs/arithmetic/comparison.py
qualtran/bloqs/arithmetic/permutation.py
qualtran/bloqs/arithmetic/sorting.py
qualtran/bloqs/block_encoding/linear_combination.py
qualtran/bloqs/block_encoding/product.py
qualtran/bloqs/block_encoding/tensor_product.py
qualtran/bloqs/data_loading/select_swap_qrom.py
qualtran/bloqs/qft/qft_text_book.py
qualtran/bloqs/rotations/phase_gradient.py
qualtran/bloqs/state_preparation/prepare_uniform_superposition.py
qualtran/bloqs/state_preparation/state_preparation_via_rotation.py
qualtran/symbolics/types.py

This change adds `TypeIs` to the signature of `is_symbolic`, thereby making spurious static type checker errors less likely and enabling us to remove uses of `cast` and `assert`.
A common pattern in the codebase is as follows:
```
x: SymbolicInt = ...
if is_symbolic(x):
raise DecomposeTypeError(...)
c = "abcde"[x]
```
Unfortunately, this pattern doesn't play well with static type checkers such as mypy, which we use.
As an example we actually encountered, consider this snippet from #1089 (just prior to commit 23577b27fb54f8bc5d88da05521fa092c6843a04):
```
if is_symbolic(self.k, self.offset):
raise DecomposeTypeError(f"Cannot decompose symbolic {self=}")
for start in range(0, self.k, 2 * self.offset):
for step in range(self.offset):
```
Given the above code, mypy fails with the error:
``` …
```

Make static type checking work better with symbolics

---

dev_tools/autogenerate-bloqs-notebooks-v2.py
qualtran/bloqs/arithmetic/__init__.py
qualtran/bloqs/arithmetic/multiplication.ipynb
qualtran/bloqs/arithmetic/multiplication.py
qualtran/bloqs/arithmetic/multiplication_test.py
qualtran/bloqs/arithmetic/subtraction.py
qualtran/serialization/resolver_dict.py

Cost out the arithmetic operation of inverting a real number >= 1. Uses Newton-Raphson iteration as specified by [this reference](https://arxiv.org/pdf/1511.08253).
This bloq can be combined with inverse square root to compute the square root of a number.

Add `InvertRealNumber` bloq

---

dev_tools/autogenerate-bloqs-notebooks-v2.py
qualtran/bloqs/arithmetic/__init__.py
qualtran/bloqs/arithmetic/subtraction.ipynb
qualtran/bloqs/arithmetic/subtraction.py
qualtran/bloqs/arithmetic/subtraction_test.py
qualtran/serialization/resolver_dict.py

Add a new version of `Subtract` that instead of taking $|a\rangle|b\rangle \mapsto |a\rangle|a-b\rangle$, takes it to $|a\rangle|b-a\rangle$. This is essentially equivalent to the statement `b -= a`.
The implementation uses an additional `Negate`, which could likely be improved, but this is a first approach. For now, it only supports `a` and `b` register of equal dtype.
The reason we need this for `Subtract` but not for `Add` is because addition is commutative and we could always swap the operands, but we can't for subtraction.

Add `SubtractFrom` to subtract from a register in place

---

qualtran/bloqs/arithmetic/multiplication.ipynb
qualtran/bloqs/arithmetic/subtraction.py

Switch the implementation of `SubtractFrom` to use `BitwiseNot` rather than `Negate` to save some Toffolis as per [suggestion](https://github.com/quantumlib/Qualtran/pull/1158#discussion_r1683629710).

Switch `SubtractFrom` to use `BitwiseNot`

---

dev_tools/autogenerate-bloqs-notebooks-v2.py
qualtran/bloqs/block_encoding/__init__.py
qualtran/bloqs/block_encoding/block_encoding.ipynb
qualtran/bloqs/block_encoding/sparse_matrix.py
qualtran/bloqs/block_encoding/sparse_matrix_test.py
qualtran/conftest.py
qualtran/serialization/resolver_dict.py

Add an instance of `BlockEncoding` that builds a block encoding of a sparse-access matrix given
oracles for the indices of non-zero entries in each row / column and an oracle for its entries.
For now, we test its behavior using oracles for a matrix with the same entry in every position.
Oracles for diagonal and tridiagonal matrices are planned next.

Create `SparseMatrix` block encoding

---

check/autogenerate-notebooks

This script can be useful in a manual or CI test that a PR has appropriately updated the notebooks associated with a code change.
Running `check/autogenerate-notebooks` will either return 0 if `dev_tools/autogenerate-bloqs-notebooks-v2.py` leaves the Git working directory clean, or return 1 and print a message like the following:
```
...
[hamiltonian_simulation_by_gqsp] Replacing HamiltonianSimulationByGQSP.call_graph.py cell.
M qualtran/bloqs/block_encoding/block_encoding.ipynb
```

Add script to check whether autogenerating notebooks is idempotent

---

qualtran/bloqs/block_encoding/product_test.py

These tests increase confidence in the correctness of the implementation. They are pretty fast to run.

Add random tests for `Product` block encoding

---

qualtran/resource_counting/_bloq_counts.py
qualtran/surface_code/algorithm_summary.py
qualtran/surface_code/algorithm_summary_test.py
qualtran/surface_code/azure_cost_model.ipynb
qualtran/surface_code/azure_cost_model.py
qualtran/surface_code/azure_cost_model_test.py
qualtran/surface_code/physical_parameters.py
qualtran/surface_code/rotation_cost_model.py
qualtran/surface_code/rotation_cost_model_test.py
qualtran/surface_code/ui.py

This PR builds on #1154 and migrates the azure model to use `GateCounts` via a new `AlgorithmSummary` that uses `GateCounts`.

[surface code] Azure model and new AlgorithmSummary

---

qualtran/_infra/data_types.py

Add some `is_symbolic` checks to `__attrs_post_init__` in `QFxp`.

Fix checking of symbolics in `QFxp`

---

qualtran/bloqs/block_encoding/block_encoding.ipynb
qualtran/bloqs/block_encoding/sparse_matrix.py
qualtran/bloqs/block_encoding/sparse_matrix_test.py
qualtran/conftest.py

Enables symbolic resource counting for `SparseMatrix` block encoding.

Add symbolic call graph for `SparseMatrix`

---

qualtran/bloqs/arithmetic/permutation.ipynb
qualtran/bloqs/arithmetic/permutation.py
qualtran/bloqs/arithmetic/permutation_test.py
qualtran/bloqs/block_encoding/block_encoding.ipynb
qualtran/bloqs/block_encoding/sparse_matrix.py
qualtran/bloqs/block_encoding/sparse_matrix_test.py
qualtran/bloqs/state_preparation/prepare_uniform_superposition.py
qualtran/bloqs/state_preparation/prepare_uniform_superposition_test.py
qualtran/bloqs/state_preparation/state_preparation_alias_sampling_test.py
qualtran/symbolics/math_funcs.py
qualtran/symbolics/math_funcs_test.py

The previous symbolic expression was `ceil(log2(x))` which is incorrect (e.g. `n=4`). This refactor uses a single correct expression for both symbolic and non-symbolic cases.
- Added a test to verify the new expression matches.
- This also simplifies some awkward looking symbolic terms, e.g. `ceil(log2(2**n - 1))` to `n` (when `n` is a sympy symbol declared with `positive=True, integer=True`)

Fix symbolic expression in `bit_length`

---

qualtran/bloqs/arithmetic/multiplication.ipynb
qualtran/bloqs/arithmetic/multiplication.py
qualtran/bloqs/basic_gates/z_basis.py

Fix dtypes in IntVector and PlusEqualsProduct

---

qualtran/_infra/data_types.py
qualtran/_infra/data_types_test.py
qualtran/simulation/classical_sim.py
qualtran/simulation/classical_sim_test.py

Adds `from_bits_array` and `to_bits_array`, and uses these functions in classical_sim's `ints_to_bits` and `bits_to_ints` (which will be removed in a follow up PR).
part of #1142

Add vectorized `from_bits` and `to_bits`

---

qualtran/bloqs/bookkeeping/auto_partition.py
qualtran/bloqs/bookkeeping/auto_partition_test.py

Fix a bug in `AutoPartition` where having `Unused` assigned to the same position in two different exposed registers would map them to the same internal `_unused` register and break decomposition.

Fix `AutoPartition` indexing bug with multiple `Unused`

---

qualtran/bloqs/block_encoding/chebyshev_polynomial.ipynb
qualtran/bloqs/block_encoding/chebyshev_polynomial.py
qualtran/bloqs/block_encoding/chebyshev_polynomial_test.py
qualtran/conftest.py

- Migrate `ChebyshevPolynomial` to the modern `BlockEncoding` interface by changing the base class, attribute type, and signature.
- Clarify in the docstring that `ChebyshevPolynomial` only works correctly with block encodings $\mathcal{B}[A]$ of Hermitian matrices $A$.
- Make `ChebyshevPolynomial` correct for use with non-Hermitian block encodings $\mathcal{B}[A] \neq \mathcal{B}[A]^\dagger$, following the existing reference.
The last change involves invoking $\mathcal{B}[A]^\dagger$. Most of our block encodings are not Hermitian, making this necessary for correctness. The total number of invocations of $\mathcal{B}[A]$ and its adjoint remains equal to the specified order of the Chebyshev polynomial.
There are no existing users of `ChebyshevPolynomial` to update.

Revamp `ChebyshevPolynomial`

---

qualtran/bloqs/basic_gates/identity.py
qualtran/bloqs/basic_gates/su2_rotation.py
qualtran/bloqs/basic_gates/swap.py
qualtran/bloqs/basic_gates/t_gate.py
qualtran/bloqs/basic_gates/toffoli.py
qualtran/bloqs/block_encoding/block_encoding_base.py
qualtran/bloqs/block_encoding/lcu_block_encoding.py
qualtran/bloqs/block_encoding/linear_combination.py
qualtran/bloqs/block_encoding/phase.py
qualtran/bloqs/block_encoding/product.py
qualtran/bloqs/block_encoding/sparse_matrix.py
qualtran/bloqs/block_encoding/tensor_product.py
qualtran/bloqs/block_encoding/unitary.py
qualtran/bloqs/bookkeeping/auto_partition.py
qualtran/bloqs/chemistry/hubbard_model/qubitization/prepare_hubbard.py
qualtran/bloqs/chemistry/hubbard_model/qubitization/select_hubbard.py
qualtran/bloqs/chemistry/pbc/first_quantization/projectile/select_and_prepare.py
qualtran/bloqs/chemistry/pbc/first_quantization/select_and_prepare.py
qualtran/bloqs/mcmt/and_bloq.py
qualtran/bloqs/mcmt/multi_control_multi_target_pauli.py
qualtran/bloqs/phase_estimation/text_book_qpe.py
qualtran/bloqs/qubitization/qubitization_walk_operator.py
qualtran/bloqs/state_preparation/prepare_uniform_superposition.py
qualtran/bloqs/state_preparation/state_preparation_alias_sampling.py
qualtran/bloqs/swap_network/cswap_approx.py
qualtran/bloqs/swap_network/multiplexed_cswap.py
qualtran/bloqs/swap_network/swap_with_zero.py

These `import_line`s are all equivalent to the default generated by `BloqDocSpec`.
There may be more that are technically redundant but are different from their current state in the notebook (i.e. import from a child rather than parent module). They can be addressed in a follow-up PR.

Remove redundant import_line from BloqDocSpec

---

qualtran/_infra/data_types.py
qualtran/bloqs/bookkeeping/cast.py
qualtran/bloqs/bookkeeping/cast_test.py
qualtran/bloqs/bookkeeping/join.py
qualtran/bloqs/bookkeeping/partition.py
qualtran/bloqs/bookkeeping/split.py
qualtran/bloqs/for_testing/casting.py
qualtran/simulation/classical_sim.py
qualtran/simulation/classical_sim_test.py

Final part of #1142!
- Remove classical sim `ints_to_bits` and `bits_to_ints`, and always use QDType bit interfaces (`from_bits, to_bits` etc.).
- Update all bookeeping bloqs to use the QDType bit features. 
Fixes #811 
Fixes #606 
Fixes #643

Use QDType bit interfaces for classical simulation

---

qualtran/bloqs/block_encoding/linear_combination.py
qualtran/bloqs/block_encoding/linear_combination_test.py

- Ensure that `alpha` in `LinearCombination` is correctly scaled by $||\lambda||$
- Correctly scale coefficient $\lambda_i$ by $\alpha_i$ when constituent block encoding has $\alpha_i \neq 1$
- Update tests to compare $A = (A/\alpha)\alpha$ with the top-left block of $\mathcal{B}[A]$

Fix `alpha` in `LinearCombination`

---

qualtran/bloqs/block_encoding/rewrites.py
qualtran/bloqs/block_encoding/rewrites_test.py

This rewrite rule reduces the resource cost of nested `LinearCombinations` by flattening them.

Add an optimizer for `LinearCombination`s

---

qualtran/bloqs/block_encoding/block_encoding_base.py
qualtran/bloqs/block_encoding/chebyshev_polynomial.py
qualtran/bloqs/block_encoding/chebyshev_polynomial_test.py
qualtran/bloqs/block_encoding/linear_combination.py
qualtran/bloqs/block_encoding/phase.py
qualtran/bloqs/block_encoding/product.py
qualtran/bloqs/block_encoding/sparse_matrix.py
qualtran/bloqs/block_encoding/tensor_product.py
qualtran/bloqs/block_encoding/unitary.py

These methods have been superceded by corresponding `bitsize` methods.

Remove legacy register methods from `BlockEncoding` interface

---

qualtran/bloqs/block_encoding/block_encoding_base.py
qualtran/bloqs/block_encoding/lcu_block_encoding.py
qualtran/bloqs/chemistry/df/double_factorization.py
qualtran/bloqs/chemistry/sf/single_factorization.py

See #1247.
These methods were not previously marked as abstract due to not being implemented in chemistry block encodings.

Make methods `abstractmethod` in `BlockEncoding`

---

qualtran/bloqs/block_encoding/block_encoding_base.py
qualtran/bloqs/block_encoding/chebyshev_polynomial.py
qualtran/bloqs/block_encoding/chebyshev_polynomial_test.py
qualtran/bloqs/block_encoding/linear_combination.py
qualtran/bloqs/block_encoding/phase.py
qualtran/bloqs/block_encoding/product.py
qualtran/bloqs/block_encoding/sparse_matrix.py
qualtran/bloqs/block_encoding/tensor_product.py
qualtran/bloqs/block_encoding/unitary.py
qualtran/bloqs/chemistry/df/double_factorization.py
qualtran/bloqs/chemistry/sf/single_factorization.py

The `BlackBoxPrepare` signature, with its single `junk` and `selection` registers, is appropriate to use for us to implement `signal_state`.

Switch `BlockEncoding.signal_state` to `BlackBoxPrepare`

---

qualtran/bloqs/for_testing/atom.py
qualtran/drawing/_show_funcs.py
qualtran/drawing/bloq_counts_graph.py
qualtran/drawing/bloq_counts_graph_test.py
qualtran/resource_counting/_bloq_counts.py
qualtran/resource_counting/_bloq_counts_test.py
qualtran/resource_counting/call_graph.ipynb
qualtran/surface_code/beverland_et_al_model.py

This adds a new factory method `GraphvizCallGraph.from_bloq` that will set up a nice call graph for you
- It takes a bloq, and will generate the networkx call graph
- It will query `QECGatesCost` and `QubitCount`
- It will take those two things and draw them in a nice way. I added class methods to format the cost values, which could theoretically be overridden by an intrepid customizer.
Some drive-by improvements to handling symbolics in `GateCounts`. 
I've also modified the `show_call_graph` convenience function to dispatch based on the input type: If it's a graph (like before) it will use the previous code path (which will eventually be deprecated when I go through and make sure all the bloqs have good-enough `__str__` values). If a bloq is provided, it will use the new functionality. …

`GraphvizCallGraph.from_bloq`

---

dev_tools/requirements/deps/runtime.txt
dev_tools/requirements/envs/dev.env.txt
dev_tools/requirements/envs/docs.env.txt
dev_tools/requirements/envs/format.env.txt
dev_tools/requirements/envs/pip-tools.env.txt
dev_tools/requirements/envs/pylint.env.txt
dev_tools/requirements/envs/pytest.env.txt
dev_tools/requirements/envs/runtime.env.txt

Supersedes #1267 
This adds unpinned bartiq and qref to the runtime dependencies and re-compiles our set of pinned dependencies (used for the ci). I split this into two commits so you can see the changes from 1) regularly updating the pinned dependencies and 2) changes due solely to the new packages.
Adding bartiq and qref doesn't really introduce any new dependencies. One note: the `graphviz` pypi package doesn't actually install graphviz the program, but is a Python utility library for manipulating graphviz files. In qualtran we use pydot which is the same idea, albeit with a less confusing name :)
cc @mstechly

Ad bartiq and qref as dependencies for interop

---

dev_tools/autogenerate-bloqs-notebooks-v2.py
docs/bloqs/index.rst
qualtran/bloqs/arithmetic/__init__.py
qualtran/bloqs/arithmetic/controlled_addition.ipynb
qualtran/bloqs/arithmetic/controlled_addition.py
qualtran/bloqs/arithmetic/controlled_addition_test.py
qualtran/serialization/resolver_dict.py

This is a followup PR to https://github.com/quantumlib/Qualtran/pull/864 that
- adds a notebook for CAdd
- fixes classical action and adds classical action tests
- replaces the decomposition. The old decomposition is buggy and failed classical tests. Instead I use a simple decomposition that uses $n$ ancillas.
- adds tests for decomposition and symbolic costs
PS: we should probably replace this decomposition with the old one when we fix the bug in the old one.

Improve support for CAdd

---

qualtran/bloqs/state_preparation/state_preparation_via_rotation.py
qualtran/bloqs/state_preparation/state_preparation_via_rotation_test.py

Fix failing test due to https://github.com/quantumlib/Qualtran/pull/1276
We should use counters to add up bloqs in `build_call_graph` methods. Pattern like `return {bloq: 1, bloq.adjoint(): 1}` leads to undercounting when `bloq` and `bloq.adjoint()` are same (i.e. a bloq is self-inverse, which is what happened here with `QROM`)

Fix `PRGAViaPhaseGradient.build_call_graph` to use `Counter` instead of `Dict`

---

qualtran/bloqs/basic_gates/_shims.py
qualtran/resource_counting/_bloq_counts.py
qualtran/resource_counting/_bloq_counts_test.py

Introduces a simple shim bloq `Measure` for single qubit measurements. Useful for resource counting, e.g. #1135

Add shim for measurement gate

---

dev_tools/requirements/deps/runtime.txt
dev_tools/requirements/envs/dev.env.txt
dev_tools/requirements/envs/docs.env.txt
dev_tools/requirements/envs/format.env.txt
dev_tools/requirements/envs/pylint.env.txt
dev_tools/requirements/envs/pytest.env.txt
dev_tools/requirements/envs/runtime.env.txt

Given compatibility issues that @mpharrigan mentioned [here](https://github.com/quantumlib/Qualtran/pull/1267#issuecomment-2278298079), I made a new Bartiq release that solves it and updated versions here.

Update dependencies for newer qref & bartiq versions

---

qualtran/bloqs/data_loading/select_swap_qrom.py
qualtran/bloqs/data_loading/select_swap_qrom_test.py
qualtran/bloqs/swap_network/swap_with_zero.py
qualtran/bloqs/swap_network/swap_with_zero_test.py

Part of a series of PRs to address #368 
This PR adds:
- Explicit on_classical_vals and adjoint for `SwapWithZero` bloq. 
- Lots of tests to verify classical simulation of `SelectSwapQROM` (and it's decomposition) and `SwapWithZero`.

Add explicit adjoint for `SwapWithZero` and classical simulation tests for decomposition of `SelectSwapQROM`

---

dev_tools/autogenerate-bloqs-notebooks-v2.py
docs/bloqs/index.rst
qualtran/bloqs/data_loading/__init__.py
qualtran/bloqs/data_loading/qroam_clean.ipynb
qualtran/bloqs/data_loading/qroam_clean.py
qualtran/bloqs/data_loading/qroam_clean_test.py
qualtran/bloqs/data_loading/qrom.py
qualtran/bloqs/data_loading/qrom_base.py
qualtran/bloqs/data_loading/select_swap_qrom.ipynb
qualtran/bloqs/data_loading/select_swap_qrom.py
qualtran/drawing/qpic_diagram.py
qualtran/serialization/resolver_dict.py

Addresses https://github.com/quantumlib/Qualtran/issues/368
The only variation left after this is a `QROAMDirty` bloq, which allocates `k-1` dirty registers and assumes target is in 0 state initially. Since the constant factors of this construction are _very_ similar to `SelectSwapQROM` (leading order terms are identical), it's not a priority to add this version right now.
More work needs to be done to add (a) Docstrings, (b) Replace uses of `QROAM` and `QROAMTwoRegs` in chemistry using the newly added Bloqs and eventually add a decomposition for `QROAMCleanAdjoint` that uses measurement based un-computation; but everything else is setup correctly. 
Here are some pictures:

Add `QROAMClean` and `QROAMCleanAdjoint` bloqs for data loading

---

qualtran/_infra/registers.py
qualtran/_infra/registers_test.py
qualtran/bloqs/arithmetic/addition_test.py

Use sympy-symbolic-supporting `smax` instead of `max` for `Signature.n_Qubits`. 
Fixes #1298 
Does not fix and therefore keeps open:  #1261

n_qubits for symbolic signature

---

qualtran/bloqs/state_preparation/sparse_state_preparation_via_rotations.py

[`dok_array`](https://docs.scipy.org/doc/scipy-1.14.0/reference/generated/scipy.sparse.dok_array.html) should only accept only 2D arrays (based on docs), but seems to support 1D arrays in newer versions.
This bugfix assumes it only works with 2D, and invokes it correctly. Tested against scipy v1.10.0.
discussion: https://github.com/quantumlib/Qualtran/pull/1205#discussion_r1722411733

SparseStatePrep: fix bug in using `scipy.sparse.dok_array`

---

qualtran/_infra/controlled.py
qualtran/bloqs/basic_gates/hadamard.py
qualtran/resource_counting/_bloq_counts.py
qualtran/resource_counting/_bloq_counts_test.py
qualtran/resource_counting/_call_graph.py
qualtran/resource_counting/classify_bloqs.py
qualtran/resource_counting/classify_bloqs_test.py
qualtran/surface_code/algorithm_summary_test.py

The first commit is #1311 ; which can't be merged independently because it reveals errors that this PR fixes.
- account for bookeeping, identity, global phase gates
- partition rotations into clifford, t, or rotation based on their angle

[QECGatesCost] strict & account for more leaf bloqs

---

qualtran/bloqs/data_loading/qrom.py
qualtran/bloqs/data_loading/qrom_test.py
qualtran/bloqs/swap_network/swap_with_zero.py

The clifford cost due to `target_shapes` parameter was getting ignored. This PR fixes it. Also updates the `__str__` of `SwapWithZero` for better diagrams.

Bugfix in `QROM.build_call_graph` for symbolic case

---

qualtran/bloqs/data_loading/qroam_clean.py
qualtran/bloqs/data_loading/qroam_clean_test.py

Fixes https://github.com/quantumlib/Qualtran/issues/1315
This also fixes https://github.com/quantumlib/Qualtran/issues/1292 since construction of `batched_data_permuted` is now done lazily; only when the decomposition is required. Duplication of call graph mitigates the slow computation for the moment. 
cc @fdmalone

Add `QROAMCleanAdjointWrapper` to match signature of `QROAMClean` and delegate implementation to `QROAMCleanAdjoint`

---

qualtran/bloqs/basic_gates/identity.ipynb
qualtran/bloqs/basic_gates/identity.py
qualtran/bloqs/basic_gates/identity_test.py
qualtran/bloqs/reflections/prepare_identity.py
qualtran/bloqs/reflections/prepare_identity_test.py
qualtran/cirq_interop/_cirq_to_bloq.py
qualtran/cirq_interop/t_complexity_protocol.py

fixes #1207 
- `Identity` now accepts a `bitsize`, and has a single register `q` of `QAny(bitsize)`.
- `Identity(n).controlled(m)` is `Identity(n + m)`.
more discussion: https://github.com/quantumlib/Qualtran/pull/1322#issuecomment-2299989824

Make `Identity` an `n` qubit bloq

---

qualtran/bloqs/basic_gates/rotation.py
qualtran/bloqs/basic_gates/rotation_test.py
qualtran/bloqs/basic_gates/su2_rotation.py
qualtran/bloqs/basic_gates/x_basis_test.py
qualtran/bloqs/basic_gates/z_basis_test.py
qualtran/bloqs/chemistry/trotter/grid_ham/qvr.py
qualtran/bloqs/chemistry/trotter/grid_ham/qvr_test.py
qualtran/bloqs/phase_estimation/lp_resource_state.py
qualtran/bloqs/phase_estimation/lp_resource_state_test.py
qualtran/resource_counting/_bloq_counts.py
qualtran/resource_counting/classify_bloqs.py

Following #1313 -- some more changes to how we count.
- there's a QVR stub. The permanent fix would be to use qvr, but removing the erroneous t complexity is a start
- LPRSInterimPrep has a bad _t_complexity_ annotation, based on the current convention for counting CRz as one rotation
- states and effects can be counted (these would throw an error in `t_complexity`)
- drive by fixes to some str representations so it's clearer what the bloq is

[QECGatesCost] Adjustments to match t_complexity rotations, part 2

---

qualtran/bloqs/basic_gates/su2_rotation.py
qualtran/bloqs/basic_gates/su2_rotation_test.py

- add a helper `from_euler_zxz_angles`, which is another commonly used representation for SU2.
- simplify decomposition to use Rz and Rx gates.
- Use eps/3 per rotation, without any eps for global phase.

`SU2RotationGate`: add helper to construct from Euler ZXZ angles

---

qualtran/bloqs/block_encoding/linear_combination_test.py
qualtran/bloqs/block_encoding/sparse_matrix_test.py

- Switch `LinearCombination` test to use `RandomState`
- Make `RandomState` local rather than global in `SparseMatrix` test

Remove possible nondeterminism in block encoding tests

---

qualtran/bloqs/arithmetic/controlled_add_or_subtract_test.py
qualtran/bloqs/arithmetic/permutation_test.py
qualtran/bloqs/chemistry/df/double_factorization_test.py
qualtran/bloqs/chemistry/df/prepare_test.py
qualtran/bloqs/chemistry/pbc/first_quantization/prepare_nu_test.py
qualtran/bloqs/chemistry/pbc/first_quantization/prepare_uv_test.py
qualtran/bloqs/chemistry/pbc/first_quantization/projectile/prepare_nu_test.py
qualtran/bloqs/chemistry/pbc/first_quantization/projectile/prepare_uv_test.py
qualtran/bloqs/chemistry/pbc/first_quantization/projectile/select_and_prepare_test.py
qualtran/bloqs/chemistry/sparse/select_bloq_test.py
qualtran/bloqs/chemistry/thc/thc.ipynb
qualtran/bloqs/data_loading/qrom_test.py
qualtran/bloqs/mcmt/and_bloq.ipynb
qualtran/bloqs/mcmt/and_bloq.py
qualtran/resource_counting/_costing.py
qualtran/resource_counting/classify_bloqs.py
qualtran/resource_counting/classify_bloqs_test.py
qualtran/testing.py

Initial steps towards #1346 
I can only do so many of these changes in an afternoon, so all the changes in this PR make tests work for either `And` as leaf or non-leaf; and I put the leafiness behind a flag.

First preparations for making And an atomic/leaf bloq

---

qualtran/_infra/registers.py
qualtran/bloqs/bookkeeping/partition.py

throws fewer errors when registers with symbolic shapes

Use symbolics for computing register bitsizes

---

qualtran/bloqs/arithmetic/permutation.ipynb
qualtran/bloqs/arithmetic/permutation.py
qualtran/bloqs/arithmetic/permutation_test.py
qualtran/bloqs/state_preparation/state_preparation_via_rotation.ipynb
qualtran/bloqs/state_preparation/state_preparation_via_rotation.py
qualtran/bloqs/state_preparation/state_preparation_via_rotation_test.py
qualtran/conftest.py

- permutation bloqs: decompose for symbolic `N`
- stateprep rotation - check phase bitsize, raise `DecomposeTypeError` when not possible.

Support more symbolic decompositions

---

qualtran/_infra/composite_bloq.py
qualtran/_infra/composite_bloq_test.py
qualtran/cirq_interop/_cirq_to_bloq.py

Raise `DecomposeTypeError` for symbolic register shapes

---

qualtran/bloqs/arithmetic/conversions/ones_complement_to_twos_complement_test.py
qualtran/bloqs/basic_gates/toffoli.py
qualtran/bloqs/basic_gates/toffoli_test.py
qualtran/bloqs/chemistry/df/prepare_test.py
qualtran/bloqs/chemistry/df/select_bloq_test.py
qualtran/bloqs/chemistry/pbc/first_quantization/prepare_t_test.py
qualtran/bloqs/chemistry/pbc/first_quantization/projectile/prepare_t_test.py
qualtran/bloqs/chemistry/pbc/first_quantization/projectile/select_and_prepare_test.py
qualtran/bloqs/chemistry/pbc/first_quantization/projectile/select_t_test.py
qualtran/bloqs/chemistry/pbc/first_quantization/projectile/select_uv_test.py
qualtran/bloqs/chemistry/pbc/first_quantization/select_and_prepare_test.py
qualtran/bloqs/chemistry/pbc/first_quantization/select_t_test.py
qualtran/bloqs/chemistry/pbc/first_quantization/select_uv_test.py
qualtran/bloqs/chemistry/sf/prepare_test.py
qualtran/bloqs/chemistry/sf/single_factorization_test.py
qualtran/bloqs/chemistry/trotter/grid_ham/inverse_sqrt_test.py
qualtran/bloqs/for_testing/costing_test.py
qualtran/resource_counting/_bloq_counts.py
qualtran/resource_counting/_bloq_counts_test.py
qualtran/resource_counting/_costing_test.py

Fixes #1386 , which is part of the roadmap item #873 
Toffoli's should be counted directly. There's no existing circuit for doing the gate with 4 toffolis, but one can be added later as a bespoke method. 
All of the test changes are very straightforward: many of them were trying to test toffoli count anyways :)

Make Toffoli an atomic, leaf bloq

---

qualtran/bloqs/rotations/programmable_ancilla_rotation.py
qualtran/bloqs/rotations/programmable_ancilla_rotation_test.py

The expected symbolic cost should be 
Right now, it is
where a new `\epsilon0` symbol is introduced. This PR fixes this behavior and adds a test. 
The test should be updated after https://github.com/quantumlib/Qualtran/issues/1250 is fixed

Make symbolic call graph and costs of `ZPowUsingProgrammedAncilla` more accurate

---

qualtran/bloqs/data_loading/qroam_clean.py
qualtran/bloqs/data_loading/qroam_clean_test.py
qualtran/bloqs/data_loading/qrom.py
qualtran/bloqs/data_loading/select_swap_qrom.py
qualtran/bloqs/data_loading/select_swap_qrom_test.py

See updated test, which would fail earlier but passes now. 
Also made other drive by improvements like:
1. Fix the logic of `get_optimal_log_block_size_clean_ancilla` so it returns an integer >=0.
2. Pass ` target_bitsizes` to `QROAMCleanAdjoint` from` QROAMCleanAdjointWrapper` so that target bitsize remains the same post delegation when constructing the bloq for data. 
3. Update `find_optimal_log_block_size` implementation for `SelectSwapQROM` to find the optimal bitsize taking into account a factor of 2 for dirty ancillas. Added a test to verify the new block size leads to smaller counts. 
4. Raise a `DecomposeTypeError` for `QROM` decomposition when `self.has_data()` is false. This makes qubit counting protocols deal with symbolic qroms better.

Bugfix in `QROAMCleanAdjointWrapper` to correctly pass `num_controls` to `QROAMCleanAdjoint`

---

qualtran/bloqs/factoring/mod_exp.ipynb
qualtran/bloqs/factoring/mod_exp.py
qualtran/bloqs/factoring/mod_exp_test.py
qualtran/bloqs/mod_arithmetic/mod_multiplication.py

Fixes https://github.com/quantumlib/Qualtran/issues/1398
```
%%time
show_call_graph(_modexp_small.make())
```
now takes ~40seconds on my laptop. I'd say this is slow; cc https://github.com/quantumlib/Qualtran/issues/957

Fix parameter values for `ModExp` examples and add post init assertions for better error messages

---

qualtran/bloqs/mod_arithmetic/mod_addition.py

Replicate bug with ModAdd(bitsize=8, mod=17).adjoint().on_classical_vals(x=0,y=0). Basically, we do signed integer addition with registers that have unsigned dtypes. Change the intermediate register dtypes to QInt to perform modular reductions then restore to unsigned int dtypes.

Maked intermediate additions unsigned in ModAdd

---

qualtran/bloqs/arithmetic/comparison.py
qualtran/bloqs/arithmetic/comparison_test.py

bloq introduced in #1411 had some extra bloqs in the call graph

fix call graph for `Equals`

---

.github/workflows/ci.yaml
dev_tools/qualtran_dev_tools/notebook_execution.py
dev_tools/requirements/deps/runtime.txt
dev_tools/requirements/envs/dev.env.txt
dev_tools/requirements/envs/docs.env.txt
dev_tools/requirements/envs/format.env.txt
dev_tools/requirements/envs/pip-tools.env.txt
dev_tools/requirements/envs/pylint.env.txt
dev_tools/requirements/envs/pytest.env.txt
dev_tools/requirements/envs/runtime.env.txt
qualtran/__init__.py
qualtran/_infra/data_types.py
qualtran/_infra/data_types_test.py
qualtran/simulation/classical_sim.py
qualtran/simulation/classical_sim_test.py

Part of https://github.com/quantumlib/Qualtran/issues/1419
Serialization support for new QDType will be added in a follow up PR

Add QGF data type for Galois Fields

---

qualtran/bloqs/bookkeeping/partition.py
qualtran/bloqs/bookkeeping/partition_test.py

Part of a larger effort to support galois field arithmetic in Qualtran xref https://github.com/quantumlib/Qualtran/issues/1419
Bugfix related to the effort of reducing friction for adding new data types that aren't integers xref https://github.com/quantumlib/Qualtran/issues/1437
See added test, that fails on main but passes after the PR.

Bugfix in Partition to support QGF type registers

---

qualtran/_infra/adjoint.py
qualtran/_infra/bloq.py
qualtran/bloqs/arithmetic/conversions/contiguous_index.py
qualtran/bloqs/basic_gates/cnot.py
qualtran/bloqs/basic_gates/global_phase.py
qualtran/bloqs/basic_gates/hadamard.py
qualtran/bloqs/basic_gates/identity.py
qualtran/bloqs/basic_gates/rotation.py
qualtran/bloqs/basic_gates/s_gate.py
qualtran/bloqs/basic_gates/swap.py
qualtran/bloqs/basic_gates/toffoli.py
qualtran/bloqs/basic_gates/x_basis.py
qualtran/bloqs/basic_gates/y_gate.py
qualtran/bloqs/basic_gates/z_basis.py
qualtran/bloqs/bookkeeping/_bookkeeping_bloq.py
qualtran/bloqs/bookkeeping/arbitrary_clifford.py
qualtran/bloqs/for_testing/atom.py
qualtran/bloqs/mcmt/and_bloq.py
qualtran/cirq_interop/_bloq_to_cirq.py
qualtran/cirq_interop/_bloq_to_cirq_test.py
qualtran/cirq_interop/_cirq_to_bloq.py
qualtran/cirq_interop/t_complexity_protocol.py
qualtran/cirq_interop/t_complexity_protocol_test.py
qualtran/cirq_interop/testing.py
qualtran/cirq_interop/testing_test.py
qualtran/resource_counting/_bloq_counts.py
qualtran/serialization/bloq_test.py

Final part of #1251 
This PR removes the legacy `_t_complexity_` override from all bloqs. These were already redundant: during development of previous PRs I had removed use of these anyways. Those PRs did careful accounting of all `bloq_example` and unit test t complexity values and made sure they matched the `QECGatesCost` values (with some small, contained legacy shims). This PR shows that off!
See my inline comments, but I left in a `getattrs`-based shim so that the `_t_complexity_` override will still be used if `QECGatesCost()` is in legacy mode. The only thing left in qualtran that uses it is a specific unit test I added to test it.

Remove _t_complexity_

---

qualtran/bloqs/gf_arithmetic/gf2_multiplication.ipynb
qualtran/bloqs/gf_arithmetic/gf2_multiplication.py
qualtran/bloqs/gf_arithmetic/gf2_multiplication_test.py

Updates the existing `GFMultiplication` bloq to support an in-place `PlusEqualProduct` version of the bloq where the multiplied integer gets added to the result register. The decomposition is _very_ similar except we need an inverse of the linear reversible circuit at the beginning, so I decided to add this as a special case controlled by a flag instead of adding a new Bloq. 
Part of a larger effort to support galois field arithmetic in qualtran. xref https://github.com/quantumlib/Qualtran/issues/1419

`PlusEqualProduct` version of `GFMultiplication` for GF($2^m$)

---

qualtran/bloqs/gf_arithmetic/gf2_inverse.ipynb
qualtran/bloqs/gf_arithmetic/gf2_inverse.py
qualtran/bloqs/gf_arithmetic/gf2_inverse_test.py

This PR improves the T complexity of `GF2Inverse` from O(m^3) to O(m^2log(m)) following construction from https://arxiv.org/pdf/1209.6348
Updates the tests and adds references.

Optimized implementation of `GF2Inverse`

---

dev_tools/ui-export.ipynb

Previously, the JSON export for the web app did not export documentation for Bloqs with no examples. This fixes that, which is a prerequisite for b/372965588.

[qwa] Export docs for bloqs without examples

---

qualtran/bloqs/mod_arithmetic/mod_division.py
qualtran/bloqs/mod_arithmetic/mod_division_test.py

this was missed in https://github.com/quantumlib/Qualtran/pull/1464

Override KaliskiModInverse.adjoint

---

dev_tools/qualtran_dev_tools/notebook_specs.py
docs/bloqs/index.rst
qualtran/bloqs/block_encoding/__init__.py
qualtran/bloqs/block_encoding/sparse_matrix_hermitian.ipynb
qualtran/bloqs/block_encoding/sparse_matrix_hermitian.py
qualtran/bloqs/block_encoding/sparse_matrix_hermitian_test.py
qualtran/conftest.py

Implements a Hermitian block-encoding $U$ of a sparse matrix $A$. i.e. the unitary $U$ is Hermitian, or equivalently, a reflection. This is useful to directly build an efficient walk operator, for example in #1348 
Ref: https://arxiv.org/abs/2201.08309, Ch. 6.5. Proposition 6.8, Fig 6.7.

Add `SparseMatrixHermitian` block-encoding

---

qualtran/bloqs/mod_arithmetic/mod_division.py
qualtran/bloqs/mod_arithmetic/mod_division_test.py

By construction KaliskiModInverse assumes its inputs are valid (i.e. gcd(x, mod) = 1). The case of zero is interesting however since for the bloq to be unitary it has to send zero to itself. the default circuit either does that or sends it to $p$ depending on whether the opreation $p - r$ is implemented as `ModNeg` $\mathcal{O}(2n)$ 
toffoli or as ~r -> AddK($p + 1$)  $\mathcal{O}(n)$ toffoli (which is what we do).
Changing the final step to use ModNeg solves the problem (but increases the toffoli costs by $n$). it also prevents us from freeing the $u$ and $s$  registers so we will have to keep them around for uncomputation. This means we keep $6n$ junk qubits.
Alternatively we can do this at no additional cost and by keeping only $4n$ junk qubits. The condition $x=0$ or more precisely …

Modify KaliskiModInverse to support zero

---

qualtran/_infra/controlled.py
qualtran/_infra/controlled_test.py
qualtran/bloqs/mcmt/ctrl_spec_and.ipynb
qualtran/bloqs/mcmt/ctrl_spec_and.py
qualtran/bloqs/mcmt/ctrl_spec_and_test.py
qualtran/conftest.py
qualtran/serialization/ctrl_spec.py
qualtran/simulation/tensor/_tensor_data_manipulation.py
qualtran/symbolics/math_funcs.py
qualtran/symbolics/math_funcs_test.py
qualtran/symbolics/types.py
qualtran/symbolics/types_test.py

- update element type of `CtrlSpec.cvs` from `NDArray` to `Union[NDArray, Shaped]`
- add tests for symbolic ctrl-specs
- move some `qualtran.symbolics` code to more appropriate files.
fixes #1168

Support symbolic `CtrlSpec`

---

qualtran/bloqs/arithmetic/addition.ipynb
qualtran/bloqs/arithmetic/addition.py
qualtran/bloqs/arithmetic/addition_test.py
qualtran/bloqs/arithmetic/negate.py
qualtran/bloqs/block_encoding/sparse_matrix.py
qualtran/bloqs/mod_arithmetic/mod_addition.py
qualtran/bloqs/mod_arithmetic/mod_division.py
qualtran/bloqs/mod_arithmetic/mod_multiplication.py
qualtran/bloqs/mod_arithmetic/mod_subtraction.py
qualtran/bloqs/rotations/rz_via_phase_gradient_test.py
qualtran/resource_counting/classify_bloqs.py

- use attribute `dtype` instead of bitsize
- use new control specialization infrastructure
fixes #1217

Upgrade `AddK` - use dtype and simplify controls

---

qualtran/bloqs/phase_estimation/qubitization_qpe_test.py
qualtran/bloqs/phase_estimation/text_book_qpe_test.py

Cirq simulator was unable to simulate `Controlled(QubitizationWalkOperator)`, so decompose one level further to get simulable gates.
Also made a subset fast tests to catch issues early on. Fixes the current Nightly test failure.

Fix QPE cirq simulation tests 

---

qualtran/bloqs/arithmetic/comparison.py
qualtran/bloqs/factoring/ecc/ec_add_test.py
qualtran/bloqs/mod_arithmetic/mod_division.py
qualtran/bloqs/mod_arithmetic/mod_division_test.py

There was bug in the decomposition of KaliskiStep3 where a variable `junk` was assigned twice and freed twice.
there were also a few minor things in classical action of other bloqs. the reason these were not caught before is that the tests are written for the top level KaliskiModInverse which decomposes into _KaliskiIteration ... so the classically action of the _KaliskiIteration was tested, but the decomposition of _KaliskiIteration into steps wasn't. so I added tests to check all decomposition down the decomposition of each step

Fix bug in KaliskiStep3 and add tests for all steps

---

qualtran/bloqs/arithmetic/comparison.py
qualtran/bloqs/arithmetic/controlled_addition.py
qualtran/bloqs/factoring/_factoring_shims.py
qualtran/bloqs/factoring/ecc/ec_add.py
qualtran/bloqs/factoring/ecc/ec_add_r.py
qualtran/bloqs/factoring/ecc/ec_phase_estimate_r.py
qualtran/bloqs/factoring/ecc/find_ecc_private_key.py
qualtran/bloqs/mod_arithmetic/mod_division.py
qualtran/bloqs/mod_arithmetic/mod_multiplication.py

- Adds symbolic type checking for remaining ECC bloqs (https://github.com/quantumlib/Qualtran/issues/1476)
- Adds DecomposeTypeErrors for bloqs which can't be symbolically decomposed
- Both call graphs for factoring phase estimates work for symbolic arguments
- Adds decomposition for MeasureQFT bloq to allow for call graphs of the phase estimation bloqs

Fix symbolic call graphs for factoring phase estimates

---

qualtran/bloqs/block_encoding/sparse_matrix_hermitian.py
qualtran/bloqs/mcmt/multi_control_pauli.py
qualtran/bloqs/mod_arithmetic/mod_subtraction.py

- Self adjoint for `MCX` and `MCZ`
- fix deprecated call graph in `SparseMatrixHermitian`

Self adjoint for `MCX` and `MCZ`

---

qualtran/bloqs/basic_gates/rotation.py
qualtran/cirq_interop/_cirq_to_bloq.py
qualtran/cirq_interop/_cirq_to_bloq_test.py

When computing the t-complexity, if `_from_directly_countable_cirq` returns `None`, it now defaults to using the decomposition to compute the gate counts.
fixes #1426 - added the test described here. (the exact cost values would need to updated once #1455 is merged)

Allow computing cost from decomposition of cirq gates

---

qualtran/bloqs/chemistry/resource_estimation.ipynb

Be a bit careful about complexity of the sparse Hamiltonian

---

qualtran/bloqs/arithmetic/permutation_test.py
qualtran/bloqs/chemistry/df/double_factorization.py
qualtran/bloqs/chemistry/df/double_factorization_test.py
qualtran/bloqs/chemistry/sf/single_factorization_test.py
qualtran/bloqs/hamiltonian_simulation/hamiltonian_simulation_by_gqsp_test.py
qualtran/bloqs/mcmt/and_bloq.py
qualtran/bloqs/mcmt/specialized_ctrl_test.py
qualtran/bloqs/multiplexers/apply_lth_bloq_test.py
qualtran/drawing/bloq_counts_graph_test.py
qualtran/resource_counting/t_counts_from_sigma.py

fixes #1346 
also removes the only use of big O in call graph #1368
- first commit sets `FLAG_AND_IS_LEAF=True` and fixes all tests
- second one removes it altogether and cleans up the `And` bloq code
- fix `t_counts_from_sigma` to explicitly count `And`s

Make `And` a leaf bloq

---

dev_tools/qualtran_dev_tools/notebook_specs.py
docs/bloqs/index.rst
qualtran/bloqs/arithmetic/lists/__init__.py
qualtran/bloqs/arithmetic/lists/has_duplicates.py
qualtran/bloqs/arithmetic/lists/has_duplicates_test.py
qualtran/bloqs/arithmetic/lists/lists.ipynb
qualtran/bloqs/arithmetic/lists/sort_in_place.py
qualtran/bloqs/arithmetic/lists/symmetric_difference.py
qualtran/bloqs/arithmetic/lists/symmetric_difference_test.py
qualtran/bloqs/arithmetic/sorting.py
qualtran/conftest.py
qualtran/serialization/resolver_dict.py

implement the following primitives from https://arxiv.org/abs/2406.19378
- `SortInPlace`
- `SymmetricDifference`
- `HasDuplicates`
part of #1348

Add list primitives from Quartic speedups paper

---

dev_tools/requirements/deps/runtime.txt
dev_tools/requirements/envs/dev.env.txt
dev_tools/requirements/envs/docs.env.txt
dev_tools/requirements/envs/format.env.txt
dev_tools/requirements/envs/pip-tools.env.txt
dev_tools/requirements/envs/pylint.env.txt
dev_tools/requirements/envs/pytest.env.txt
dev_tools/requirements/envs/runtime.env.txt
qualtran/qref_interop/_bloq_to_qref.py
qualtran/qref_interop/_bloq_to_qref_test.py

This PR introduces an option to create QREF routines from callgraphs.
I have not updated the dependencies, as I decided it will be better to ask @mpharrigan for assistance :)
Since we're using strict bounds, `qref==0.9.0` and `bartiq==0.9.0` should be fine. If you want me to provide some looser bounds, I can find out what these should be.

add option to generate QREF from callgraphs

---

qualtran/bloqs/mod_arithmetic/mod_division.py
qualtran/bloqs/mod_arithmetic/mod_division_test.py
qualtran/bloqs/swap_network/cswap_approx.py
qualtran/bloqs/swap_network/swap_network.ipynb

uses `CSwap` instead of `CSwapApprox`. Fixes #1526 
ptal @NoureldinYosri @mpharrigan

Fix `CSwap` bloq in mod division

---

qualtran/bloqs/gf_arithmetic/gf2_multiplication.py
qualtran/bloqs/gf_arithmetic/gf2_multiplication_test.py

The inverse should be calculated using GF2 arithmetic.

BugFix in adjoint of `SynthesizeLRCircuit`

---

qualtran/symbolics/math_funcs.py
qualtran/symbolics/math_funcs_test.py

Fixes https://github.com/quantumlib/Qualtran/issues/1558

Update math funcs to use functions from math instead of numpy to support arbitrary length integers

---

.markdownlintrc

This configures `markdownlint`, a Markdown linter/formatter, to follow the Google style guide for Markdown as closely as possible. This allows users to use `markdownlint` when writing and editing Markdown files, and gets us ready to add a Markdown linter check in the CI workflow.

Add .markdownlintrc config file for markdownlint

---

qualtran/bloqs/qft/qft_text_book_test.py

gh-1455 included a change to test_qft_text_book_quick to respect the new, native CRz bloqs. I must have missed porting these changes to the @pytest.mark.slow version of this unit test, and the nightly build failed. This ports the changes to the slow test to fix the nightly build.

Fix test_qft_text_book following #1455

---

.github/workflows/nightly.yaml
.github/workflows/pr.yaml

This updates the GitHub Actions workflows to conform to some Google requirements and best practices:
- pin versions of GitHub Actions to commit SHAs
- pin versions of runners instead of using *-latest
- set default permissions for workflow
- set timeouts on jobs, to prevent running for 6 hrs (the default) in case of hangs or loops
This also fixes the following Scorecard security warnings:
- https://github.com/quantumlib/Qualtran/security/code-scanning/17
- https://github.com/quantumlib/Qualtran/security/code-scanning/18
- https://github.com/quantumlib/Qualtran/security/code-scanning/20
- https://github.com/quantumlib/Qualtran/security/code-scanning/21
- https://github.com/quantumlib/Qualtran/security/code-scanning/22
- https://github.com/quantumlib/Qualtran/security/code-scanning/23
- …

Add explicit versions and timeouts to GHA workflows

---

qualtran/bloqs/arithmetic/addition.py
qualtran/bloqs/arithmetic/addition_test.py
qualtran/bloqs/arithmetic/controlled_add_or_subtract_test.py

`Controlled(Add)` is no good since it will try to do `Controlled(And())` which is ill-specified. This was causing a test failure in the test I've un-marked as slow, since it's not slow.

Add Add.controlled() -> CAdd

---

.github/problem-matchers/README.md
.github/problem-matchers/black.json
.github/problem-matchers/mypy.json
.github/problem-matchers/pylint.json
.github/workflows/pr.yaml

GitHub [Problem Matchers](https://github.com/actions/toolkit/blob/main/docs/problem-matchers.md) are a mechanism that enable workflow steps to scan the outputs of GitHub Actions for regex patterns and automatically write annotations in the workflow summary page. Using Problem Matchers allows information to be displayed more prominently in the GitHub user interface.
This add problem matchers for Pylint, Mypy and Black output.

Add problem-matchers for Pylint, MyPy, and Black

---

qualtran/bloqs/chemistry/sparse/prepare.py
qualtran/bloqs/chemistry/sparse/prepare_test.py
qualtran/bloqs/chemistry/sparse/sparse.ipynb
qualtran/bloqs/data_loading/qroam_clean.ipynb
qualtran/bloqs/data_loading/qroam_clean.py
qualtran/bloqs/data_loading/select_swap_qrom_test.py

Fixes #1547 
`PrepareSparse` would fail to decompose with `log_block_size=0`, which is extra unfortunate since the automatic-block-size determination would choose this sometimes. It looks like SelectSwapQROM and QROAMClean support `log_block_size=0`, but I'd really love if @tanujkhattar or @fdmalone could give a second opinion. The bug fix itself is entirely within `PrepareSparse` -- better accounting of the qroam registers. 
Some drive-by doc formatting fixes as well

Support spare Prepare with log_block_size=0

---

qualtran/bloqs/block_encoding/lcu_block_encoding.py
qualtran/bloqs/block_encoding/lcu_block_encoding_test.py

Fixes #1592
This somehow got missed when updating the ctrl-systems for the LCU bloqs.

Add ctrl system for `LCUBlockEncoding`

---

README.md

Image URLs need to be absolute for PyPI.

Use absolute URLs for images

---

qualtran/bloqs/gf_arithmetic/gf2_multiplication_test.py

randomly choice 2 subsets of the input space to reduce the size of the test

reduce the size of test_gf2mulmod_classical_action_slow

---

qualtran/_version.py

In accordance with the docs for cutting a release, bump the version spec on `main` so I can tag the correct commit.

Bump version number for v0.6 release

---

qualtran/_version.py

In accordance with dev_tools/how-to-cut-a-release.md, so we can continue development on main and only the tagged commit will report version of 0.6.0

Bump version number to v0.7.0.dev0

---

.github/workflows/pr.yaml
dev_tools/requirements/deps/runtime.txt
dev_tools/requirements/envs/dev.env.txt
dev_tools/requirements/envs/docs.env.txt
dev_tools/requirements/envs/format.env.txt
dev_tools/requirements/envs/pylint.env.txt
dev_tools/requirements/envs/pytest.env.txt
dev_tools/requirements/envs/runtime.env.txt
qualtran/_infra/bloq.py
qualtran/_infra/bloq_test.py
qualtran/bloqs/basic_gates/cnot_test.py

Since we can't push a PyPI package that depends on a url-specified dev branch of pennylane, make a patch against the v0.6 branch to fail gracefully if you only have the existing pennylane release.

[v0.6 branch] Optional new pennylane functionality

---

dev_tools/bibliography.ipynb
dev_tools/qualtran_dev_tools/parse_docstrings.py
dev_tools/qualtran_dev_tools/parse_docstrings_test.py
qualtran/_infra/bloq.py
qualtran/bloqs/arithmetic/comparison.ipynb
qualtran/bloqs/arithmetic/comparison.py
qualtran/bloqs/basic_gates/rotation.ipynb
qualtran/bloqs/basic_gates/rotation.py
qualtran/bloqs/cryptography/ecc/ec_add_r.py
qualtran/bloqs/cryptography/ecc/ecc.ipynb
qualtran/bloqs/gf_arithmetic/gf2_inverse.ipynb
qualtran/bloqs/gf_arithmetic/gf2_inverse.py

We try to parse markdown links in the "References" section of bloq class docstrings. This fixes the final few "unparsable" ones.

Bibliography updates

---

qualtran/__init__.py
qualtran/_infra/data_types.py
qualtran/_infra/data_types_test.py

Part of a larger effort to add bloqs that perform arithmetic over polynomials with coefficients in a galois field.

[QGFPoly] Add `QGFPoly`, a new data type to represent polynomials over galois fields

---

qualtran/_infra/binst_graph_iterators.py
qualtran/_infra/binst_graph_iterators_test.py
qualtran/_infra/composite_bloq.py

There was a bug with symbolic register sizes when iterating over the bloq instances, see the comment in the added test (which used to fail)

Greedy topological sort with symbolic register sizes

---

dev_tools/qualtran_dev_tools/notebook_specs.py
docs/bloqs/index.rst
qualtran/bloqs/gf_poly_arithmetic/__init__.py
qualtran/bloqs/gf_poly_arithmetic/gf2_poly_add_k.ipynb
qualtran/bloqs/gf_poly_arithmetic/gf2_poly_add_k.py
qualtran/bloqs/gf_poly_arithmetic/gf2_poly_add_k_test.py
qualtran/bloqs/gf_poly_arithmetic/gf_poly_split_and_join.ipynb
qualtran/bloqs/gf_poly_arithmetic/gf_poly_split_and_join.py
qualtran/bloqs/gf_poly_arithmetic/gf_poly_split_and_join_test.py
qualtran/conftest.py

Part of a larger effort to add bloqs that perform arithmetic over polynomials with coefficients in a galois field.
Adds bloqs for 
- `GFPolySplit`: Split a register of type `QGFPoly` into `n + 1` registers of type `QGF` where `n` is the degree of the polynomial.
- `GFPolyJoin`: Join `n + 1` registers of type `QGF`, where `n` is the degree of the polynomial, into a register of type `QGFPoly`.
- `GF2PolyAddK`: Bloq to add a constant polynomial into a quantum register of type `QGFPoly`.

[QGFPoly] Add `GF2PolyAddK`, `GFPolySplit` and `GFPolyJoin` bloqs

---

dev_tools/requirements/deps/runtime.txt
dev_tools/requirements/envs/dev.env.txt
dev_tools/requirements/envs/docs.env.txt
dev_tools/requirements/envs/format.env.txt
dev_tools/requirements/envs/pip-tools.env.txt
dev_tools/requirements/envs/pylint.env.txt
dev_tools/requirements/envs/pytest.env.txt
dev_tools/requirements/envs/runtime.env.txt

- regularly scheduled update of our pinned dependencies for the CI
- depend on a released version of pennylane. fixes #1589. Note that the relevant interop code in qualtran is still guarded by a `try/except` to disable the functionality that's only available in pennylane>=0.41

[2025-04] Dependencies, including relased version of pennylane

---

qualtran/bloqs/cryptography/ecc/ec_add_test.py
qualtran/bloqs/data_loading/qroam_clean.py
qualtran/bloqs/data_loading/qroam_clean_test.py

Fixes https://github.com/quantumlib/Qualtran/issues/1607

BugFix in gate counts for QROAMClean for small log_block_sizes

---

dev_tools/requirements/deps/docs.txt
dev_tools/requirements/envs/docs.env.txt
docs/Makefile
docs/_static/fixes.css
docs/_static/qai-theme.css
docs/_templates/qai_logo.html
docs/_templates/qualtran-sidebar.html
docs/conf.py

This changes the colors to be the ones used by QAI and the Qualtran logo. It also adds the Qualtran logo in the upper left and the QAI logo on the bottom of the page. Finally, it changes the section headings in the sidebar to be the name of the current page instead of always being "Section navigation".

Modify Sphinx theme to use Qualtran theme colors and icons

---

qualtran/bloqs/basic_gates/rotation.py

Fixes #1148
This PR adds detailed docstrings to the `Rx` and `Ry` bloqs in `qualtran.bloqs.basic_gates.rotation`.
The docstrings now explicitly list the registers these gates operate on, improving clarity for users, as requested in issue #1148.
Specifically, the `Registers:` section has been added to:
- `Rx`
- `Ry`
This follows the existing convention for other gates like `CZPowGate` and `CHadamard`.

 Add docstrings to basic gates like CZPowGate, Rx, Ry [Unitary hack] 

---

qualtran/qref_interop/_bloq_to_qref.py

This should fix: https://github.com/quantumlib/Qualtran/issues/1657 .
From what I could say from running it locally, I stopped getting the intermittent failures in Bloq -> QREF conversion.
But you know how it is with flaky tests – in case it re-occurs, please ping me!

fix: fixes flakiness in bloq->qref conversion

---

qualtran/_infra/composite_bloq.py
qualtran/_infra/composite_bloq_test.py
qualtran/simulation/classical_sim.py
qualtran/simulation/classical_sim_test.py

- These classes will be used within the classical simulator to represent distributions of classical measurements.
- For instance, if measuring in the X-basis, you will get a random result (0 or 1) possibly with an additional phase.
- This is part of the measurement-based uncomputation feature (MBUC).
Original work done by mpharrigan in #1678

Add support for simulation over classical distributions

---

qualtran/bloqs/basic_gates/__init__.py
qualtran/bloqs/basic_gates/x_basis.py
qualtran/bloqs/basic_gates/x_basis_test.py

- MeasX measures a qubit in the X basis.
- If simulated classically, this returns a classical distribution of 0 and 1 with a possible
phase if 1 is measured.
Original work done by mpharrigan in #1678

Add bloq for Measurement in the X basis

---

qualtran/bloqs/mcmt/and_bloq.py
qualtran/bloqs/swap_network/cswap_approx.py
qualtran/cirq_interop/_cirq_to_bloq.py

- Replace `cirq.ops.op_tree.OpTree` with `cirq.OP_TREE`
- Fix flagged coefficient type for GlobalPhase
Towards #1708

Replace cirq.ops.op_tree.OpTree with cirq.OP_TREE
